using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using AiDotNet.Tensors.LinearAlgebra;

namespace AiDotNet.Tensors.Tests.Parity;

/// <summary>
/// The PyTorch feature surface (generated by <c>tools/parity/extract_pytorch_surface.py</c> from the
/// installed torch) and the checked-in record of how Tensors covers each item.
/// </summary>
/// <remarks>
/// <para>
/// <c>parity/pytorch-surface.json</c> is generated, never edited: a PyTorch release that adds a feature
/// adds it there. <c>parity/coverage.json</c> is the reviewed half: every surface item is either mapped to
/// a Tensors symbol, recorded as a gap, or marked not applicable with a reason. A mapping names a real
/// symbol, and <see cref="ResolveSymbol"/> proves it exists by reflection, so the manifest cannot claim a
/// capability the assembly does not have.
/// </para>
/// <para>
/// Symbol syntax: <c>Namespace.Type</c> for a type (optimizers), or <c>Namespace.Type::Member</c> for a
/// method or property on it, any overload. Generic types use their metadata name, e.g.
/// <c>AiDotNet.Tensors.LinearAlgebra.Tensor`1::Transpose</c>.
/// </para>
/// </remarks>
internal static class PyTorchParityInventory
{
    internal const string SurfaceFile = "parity/pytorch-surface.json";
    internal const string CoverageFile = "parity/coverage.json";

    internal enum CoverageStatus { Mapped, Gap, NotApplicable }

    internal sealed record SurfaceItem(string Category, string Name, string Signature)
    {
        public string Key => $"{Category}:{Name}";
    }

    internal sealed record CoverageEntry(CoverageStatus Status, string? Symbol, string? Reason, string Source);

    internal sealed record Surface(string TorchVersion, IReadOnlyList<SurfaceItem> Items);

    internal sealed record Coverage(string TorchVersion, int GapBaseline, IReadOnlyDictionary<string, CoverageEntry> Entries);

    /// <summary>Walks up from the test binary to the repository root that holds <c>parity/</c>.</summary>
    internal static string? FindRepositoryRoot()
    {
        for (var dir = new DirectoryInfo(AppContext.BaseDirectory); dir is not null; dir = dir.Parent)
        {
            if (File.Exists(Path.Combine(dir.FullName, SurfaceFile))) return dir.FullName;
        }

        return null;
    }

    internal static Surface LoadSurface(string root)
    {
        using var doc = JsonDocument.Parse(File.ReadAllText(Path.Combine(root, SurfaceFile)));
        var items = doc.RootElement.GetProperty("items").EnumerateArray()
            .Select(e => new SurfaceItem(
                RequiredString(e, "category"),
                RequiredString(e, "name"),
                e.TryGetProperty("signature", out var s) ? s.GetString() ?? "" : ""))
            .ToList();
        return new Surface(RequiredString(doc.RootElement, "torchVersion"), items);
    }

    internal static Coverage LoadCoverage(string root)
    {
        using var doc = JsonDocument.Parse(File.ReadAllText(Path.Combine(root, CoverageFile)));
        var entries = new Dictionary<string, CoverageEntry>(StringComparer.Ordinal);
        foreach (var property in doc.RootElement.GetProperty("entries").EnumerateObject())
        {
            var e = property.Value;
            var status = e.GetProperty("status").GetString() switch
            {
                "mapped" => CoverageStatus.Mapped,
                "gap" => CoverageStatus.Gap,
                "not-applicable" => CoverageStatus.NotApplicable,
                var other => throw new InvalidDataException($"{property.Name}: unknown status '{other}'."),
            };
            entries[property.Name] = new CoverageEntry(
                status,
                e.TryGetProperty("symbol", out var sym) ? sym.GetString() : null,
                e.TryGetProperty("reason", out var why) ? why.GetString() : null,
                e.TryGetProperty("source", out var src) ? src.GetString() ?? "manual" : "manual");
        }

        return new Coverage(
            RequiredString(doc.RootElement, "torchVersion"),
            doc.RootElement.GetProperty("gapBaseline").GetInt32(),
            entries);
    }

    private static string RequiredString(JsonElement element, string property)
        => element.GetProperty(property).GetString()
           ?? throw new InvalidDataException($"'{property}' is null in the parity manifest.");

    private static Assembly TensorsAssembly => typeof(Tensor<>).Assembly;

    /// <summary>Resolves a manifest symbol against the Tensors assembly. Returns why it failed, or null.</summary>
    internal static string? ResolveSymbol(string symbol)
    {
        string typeName = symbol;
        string? member = null;
        int split = symbol.IndexOf("::", StringComparison.Ordinal);
        if (split >= 0)
        {
            typeName = symbol.Substring(0, split);
            member = symbol.Substring(split + 2);
        }

        var type = TensorsAssembly.GetType(typeName, throwOnError: false);
        if (type is null) return $"type '{typeName}' does not exist in {TensorsAssembly.GetName().Name}";
        if (!type.IsPublic && !type.IsNestedPublic) return $"type '{typeName}' is not public";
        if (member is null) return null;

        return PublicMemberNames(type).Contains(member)
            ? null
            : $"'{typeName}' has no public member '{member}'";
    }

    /// <summary>Public methods and properties, including those an interface inherits.</summary>
    private static HashSet<string> PublicMemberNames(Type type)
    {
        const BindingFlags Flags = BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static;
        var types = new List<Type> { type };
        if (type.IsInterface) types.AddRange(type.GetInterfaces());
        var names = new HashSet<string>(StringComparer.Ordinal);
        foreach (var t in types)
        {
            foreach (var m in t.GetMethods(Flags)) names.Add(m.Name);
            foreach (var p in t.GetProperties(Flags)) names.Add(p.Name);
        }

        return names;
    }

    // ---------------------------------------------------------------------------------------------
    // Seeding: proposes an initial manifest by name. It is a starting point for review, never a claim:
    // every entry it writes is marked source "name-match", and only resolvable symbols are proposed.
    // ---------------------------------------------------------------------------------------------

    private static readonly string[] OpTypes =
    {
        "AiDotNet.Tensors.Engines.IEngine",
        "AiDotNet.Tensors.LinearAlgebra.Tensor`1",
        "AiDotNet.Tensors.NN.Functional.Functional",
        "AiDotNet.Tensors.NN.Activations.Activations",
        "AiDotNet.Tensors.NN.Losses.Losses",
    };

    private static readonly Dictionary<string, string[]> TypesByCategory = new(StringComparer.Ordinal)
    {
        ["nn.functional"] = new[]
        {
            "AiDotNet.Tensors.NN.Functional.Functional", "AiDotNet.Tensors.NN.Activations.Activations",
            "AiDotNet.Tensors.NN.Losses.Losses", "AiDotNet.Tensors.Engines.IEngine",
        },
        ["Tensor"] = new[] { "AiDotNet.Tensors.LinearAlgebra.Tensor`1", "AiDotNet.Tensors.Engines.IEngine" },
        ["torch"] = OpTypes,
        ["aten"] = OpTypes,
        ["torch.linalg"] = OpTypes,
        ["torch.fft"] = OpTypes,
    };

    /// <summary>
    /// Lowercases and strips separators, so <c>batch_norm</c>, <c>BatchNorm</c> and <c>batchnorm</c> meet.
    /// A trailing underscore (PyTorch's in-place variant) is kept distinct.
    /// </summary>
    private static string Normalize(string name)
    {
        bool inPlace = name.EndsWith("_", StringComparison.Ordinal) && !name.EndsWith("__", StringComparison.Ordinal);
        var sb = new StringBuilder();
        foreach (char c in name) if (char.IsLetterOrDigit(c)) sb.Append(char.ToLowerInvariant(c));
        return inPlace ? sb + "_inplace" : sb.ToString();
    }

    private static IEnumerable<string> CandidateMemberKeys(string memberName)
    {
        string n = Normalize(memberName);
        yield return n;
        if (n.StartsWith("tensor", StringComparison.Ordinal) && n.Length > 6) yield return n.Substring(6);
    }

    internal static JsonObject Seed(Surface surface)
    {
        var index = new Dictionary<string, Dictionary<string, string>>(StringComparer.Ordinal);
        foreach (var typeName in TypesByCategory.Values.SelectMany(v => v).Distinct())
        {
            var type = TensorsAssembly.GetType(typeName, throwOnError: false);
            if (type is null) continue;
            var byKey = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (var member in PublicMemberNames(type).OrderBy(n => n, StringComparer.Ordinal))
                foreach (var key in CandidateMemberKeys(member))
                    if (!byKey.ContainsKey(key)) byKey[key] = member;
            index[typeName] = byKey;
        }

        var optimizerTypes = TensorsAssembly.GetExportedTypes()
            .Where(t => t.Namespace is not null && t.Namespace.StartsWith("AiDotNet.Tensors.Engines.Optimization", StringComparison.Ordinal))
            .ToList();

        var entries = new JsonObject();
        foreach (var item in surface.Items)
        {
            JsonObject entry;
            if (item.Category == "nn.Module")
            {
                entry = new JsonObject
                {
                    ["status"] = "not-applicable",
                    ["reason"] = "nn.Module layers are provided by the AiDotNet framework repo, not the tensor library; covered by its parity inventory.",
                    ["source"] = "category",
                };
            }
            else if (item.Category is "optim" or "optim.lr_scheduler")
            {
                string want = Normalize(item.Name);
                var match = optimizerTypes.FirstOrDefault(t =>
                {
                    string n = Normalize(t.Name.Split('`')[0]);
                    return n == want || n == want + "optimizer" || n == want + "scheduler";
                });
                entry = match is null
                    ? new JsonObject { ["status"] = "gap", ["source"] = "name-match" }
                    : new JsonObject { ["status"] = "mapped", ["symbol"] = match.FullName, ["source"] = "name-match" };
            }
            else
            {
                string? symbol = null;
                if (TypesByCategory.TryGetValue(item.Category, out var types))
                {
                    string want = Normalize(item.Name);
                    foreach (var typeName in types)
                    {
                        if (index.TryGetValue(typeName, out var byKey) && byKey.TryGetValue(want, out var member))
                        {
                            symbol = $"{typeName}::{member}";
                            break;
                        }
                    }
                }

                entry = symbol is null
                    ? new JsonObject { ["status"] = "gap", ["source"] = "name-match" }
                    : new JsonObject { ["status"] = "mapped", ["symbol"] = symbol, ["source"] = "name-match" };
            }

            entries[item.Key] = entry;
        }

        int gaps = entries.Count(e => e.Value is JsonObject o && (string?)o["status"] == "gap");
        return new JsonObject
        {
            ["torchVersion"] = surface.TorchVersion,
            ["gapBaseline"] = gaps,
            ["entries"] = entries,
        };
    }
}
