// Copyright (c) AiDotNet. All rights reserved.
//
// Complex and quaternion kernels.
//
// This is a SEPARATE code path inside the same emitter, and that is deliberate. The real
// path's value model is a single fp32 register threaded through the operand cache, the
// shared-memory staging, the split-reduction epilogue, the coarsened lanes and the argmax
// tracking -- roughly two thousand lines that currently verify at 0.000E+000 on thirteen
// kernels. Widening that register into a component vector everywhere would put all of it at
// risk to gain nothing, because none of those mechanisms mean anything for complex
// arithmetic: there is no order to take a maximum over, the vector load path assumes
// unit-stride scalars, and staging a complex operand stages two floats that are already
// adjacent.
//
// So the real path is left byte-for-byte untouched, and an algebra kernel takes this one:
// one thread per output element, components held in adjacent registers, and the product
// driven by the algebra's multiply-accumulate table. What it will NOT do it refuses by name.

using System;
using System.Collections.Generic;
using AiDotNet.Tensors.Engines.Compilation.Codegen.Ir;

namespace AiDotNet.Tensors.Engines.Compilation.Codegen.Ptx;

public sealed partial class PtxAffineEmitter
{
    /// <summary>Real multiply-accumulates the last algebra emission produced.</summary>
    public int AlgebraProductTerms { get; private set; }

    /// <summary>
    /// Emits a complex or quaternion kernel: one thread per output element, components in
    /// adjacent registers.
    /// </summary>
    private string EmitAlgebraic(CodegenKernelSpec spec, int computeMajor, int computeMinor)
    {
        var algebra = spec.Algebra;
        int components = algebra.Components();
        var table = algebra.ProductTable();

        var space = spec.Space;
        var axes = space.Axes;
        axesMeta = axes;
        int[] parallel = space.ParallelAxes;
        int[] reduction = space.ReductionAxes;
        long total = space.TotalThreads;
        long trips = space.ReductionTripCount;

        // A long contraction becomes a RUNTIME LOOP rather than an unrolled body. Unrolling
        // without bound is how the real path produced kernels ptxas could not allocate, and a
        // quaternion body is sixteen instructions per trip, so it reaches that point four
        // times sooner. An FFT-scale contraction is exactly the case this path exists for, so
        // refusing it would have made the whole addition useless.
        bool loopReduction = trips > FullUnrollLimit;

        _sb.Clear(); _body.Clear();
        _r = _f = _p = _rd = 0;
        EmittedLoads = 0; ElidedGuards = 0; IndirectIndexLoads = 0; AtomicStores = 0;
        AlgebraProductTerms = 0;
        _inputBindings = spec.Inputs;
        Unrolled = true;
        LoopedAxes = 0;
        Coarsening = 1;
        VectorisedLoads = 0;
        StagedOperands = "none";
        SharedMemoryBytes = 0;

        int blockThreads = BlockThreads;
        LaunchBlockThreads = blockThreads;
        LaunchBlockX = blockThreads;
        LaunchBlockY = 1;
        long blocks = (total + blockThreads - 1) / blockThreads;
        CheckLimits(spec, blocks, total);
        LaunchBlocks = (uint)blocks;

        _sb.Append(".version ").Append(PtxIsaVersionFor(computeMajor, computeMinor)).Append('\n')
           .Append(".target sm_").Append(I(computeMajor)).Append(I(computeMinor)).Append('\n')
           .Append(".address_size 64\n\n")
           .Append("// generated by PtxAffineEmitter -- ").Append(algebra)
           .Append(" arithmetic, ").Append(I(components)).Append(" components per element\n")
           .Append("// ").Append(spec.Describe().Replace("\n", "\n// ")).Append('\n')
           .Append(".visible .entry ").Append(spec.Name).Append("(\n");

        int paramCount = spec.ParameterCount;
        for (int i = 0; i < paramCount; i++)
            _sb.Append("    .param .u64 p").Append(I(i)).Append(i == paramCount - 1 ? "\n" : ",\n");
        _sb.Append(")\n{\n");

        var basePtr = new string[paramCount];
        for (int i = 0; i < paramCount; i++)
        {
            basePtr[i] = NextRd();
            L($"ld.param.u64 {basePtr[i]}, [p{I(i)}];");
        }
        _basePointers = basePtr;

        string ctaid = NextR(), tid = NextR(), gid = NextR();
        L($"mov.u32 {ctaid}, %ctaid.x;");
        L($"mov.u32 {tid}, %tid.x;");
        L($"mad.lo.u32 {gid}, {ctaid}, {I(blockThreads)}, {tid};");

        string guard = NextP();
        L($"setp.ge.u32 {guard}, {gid}, {I((int)total)};");
        L($"@{guard} bra END;");

        // Decompose the flat id across parallel axes, last-declared fastest -- the same
        // decomposition the real path and the reference interpreter both use.
        var axisReg = new string[axes.Count];
        string rest = gid;
        for (int p = parallel.Length - 1; p >= 0; p--)
        {
            int ax = parallel[p];
            int extent = axes[ax].Extent;

            if (p == 0) { axisReg[ax] = rest; break; }

            string value = NextR(), next = NextR();
            L($"rem.u32 {value}, {rest}, {I(extent)};");
            L($"div.u32 {next}, {rest}, {I(extent)};");
            axisReg[ax] = value;
            rest = next;
        }

        // One accumulator per component.
        var acc = new string[components];
        for (int c = 0; c < components; c++)
        {
            acc[c] = NextF();
            L($"mov.f32 {acc[c]}, 0f00000000;");
        }

        // In the looped form the reduction axes live in REGISTERS and are handed to the
        // address arithmetic through axisReg, with an empty fold list so nothing is folded to
        // a constant. The interval analysis that derives the bounds predicate uses the axis
        // EXTENTS, which are as valid for a runtime axis as for an unrolled one.
        var reductionValues = new int[axes.Count];
        int[] foldable = loopReduction ? Array.Empty<int>() : reduction;
        string? tripCounter = null;

        if (loopReduction)
        {
            tripCounter = NextR();
            L($"mov.u32 {tripCounter}, 0;");
            _body.Append("RLOOP:\n");

            string remaining = tripCounter;
            for (int r = reduction.Length - 1; r >= 0; r--)
            {
                int extent = axes[reduction[r]].Extent;
                if (r == 0) { axisReg[reduction[r]] = remaining; break; }

                string value = NextR(), next = NextR();
                L($"rem.u32 {value}, {remaining}, {I(extent)};");
                L($"div.u32 {next}, {remaining}, {I(extent)};");
                axisReg[reduction[r]] = value;
                remaining = next;
            }
        }

        // The accumulator must live in FIXED registers across the backward branch: the
        // SSA-style renaming used inside the body cannot cross it.
        var accFixed = new string[components];
        if (loopReduction)
            for (int c = 0; c < components; c++) accFixed[c] = acc[c];

        long emittedTrips = loopReduction ? 1 : trips;
        for (long t = 0; t < emittedTrips; t++)
        {
            long rrest = t;
            if (!loopReduction)
                for (int r = reduction.Length - 1; r >= 0; r--)
                {
                    int extent = axes[reduction[r]].Extent;
                    reductionValues[reduction[r]] = (int)(rrest % extent);
                    rrest /= extent;
                }

            // Every operand, as a component vector.
            var operands = new List<string[]>(spec.ProductInputs.Count);
            string? productPred = null;
            foreach (int inputIdx in spec.ProductInputs)
            {
                var binding = spec.Inputs[inputIdx];
                operands.Add(EmitComponentLoad(
                    binding, basePtr[binding.ParameterIndex], axisReg,
                    reductionValues, foldable, components, out string? pred));
                productPred = AndPred(productPred, pred);
            }

            // The product, folded left, one algebra multiply at a time. A quaternion product
            // is NOT commutative, so the order here is the order of ProductInputs and is part
            // of the operator rather than an implementation choice.
            string[] product = operands[0];
            for (int o = 1; o < operands.Count; o++)
                product = EmitAlgebraMultiply(table, components, product, operands[o]);

            // Accumulate. An out-of-range operand already loaded zero, and zero is the
            // additive identity in every one of these algebras, so no select is needed --
            // the same argument the real path makes for Sum, and the reason Max is refused.
            for (int c = 0; c < components; c++)
            {
                string next = NextF();
                L($"add.rn.f32 {next}, {acc[c]}, {product[c]};");
                acc[c] = next;
            }
        }

        if (loopReduction)
        {
            for (int c = 0; c < components; c++)
            {
                if (!string.Equals(acc[c], accFixed[c], StringComparison.Ordinal))
                    L($"mov.f32 {accFixed[c]}, {acc[c]};");
                acc[c] = accFixed[c];
            }

            string more = NextP();
            L($"add.u32 {tripCounter}, {tripCounter}, 1;");
            L($"setp.lt.u32 {more}, {tripCounter}, {I((int)trips)};");
            L($"@{more} bra RLOOP;");
            Unrolled = false;
            LoopedAxes = reduction.Length;
        }

        if (spec.ReduceScale != 1.0)
            for (int c = 0; c < components; c++)
            {
                string scaled = NextF();
                L($"mul.rn.f32 {scaled}, {acc[c]}, {F32(spec.ReduceScale)};");
                acc[c] = scaled;
            }

        // A bias in one of these algebras is a component-wise ADD, which is the same
        // operation in all of them -- unlike the product, addition needs no table.
        if (spec.BiasInput.HasValue)
        {
            var bias = spec.Inputs[spec.BiasInput.Value];
            string[] values = EmitComponentLoad(
                bias, basePtr[bias.ParameterIndex], axisReg, reductionValues, foldable,
                components, out _);
            for (int c = 0; c < components; c++)
            {
                string next = NextF();
                L($"add.rn.f32 {next}, {acc[c]}, {values[c]};");
                acc[c] = next;
            }
        }

        // A scale operand is a full algebra multiply, not a component-wise one: scaling a
        // quaternion by a quaternion is a rotation, and doing it component-wise would be a
        // different and meaningless operation.
        if (spec.ScaleInput.HasValue)
        {
            var scale = spec.Inputs[spec.ScaleInput.Value];
            string[] values = EmitComponentLoad(
                scale, basePtr[scale.ParameterIndex], axisReg, reductionValues, foldable,
                components, out _);
            acc = EmitAlgebraMultiply(table, components, acc, values);
        }

        string outOffset = EmitOffset(spec.Output, axisReg, reductionValues, foldable,
                                      out string? outPred);
        string outBytes = NextRd(), outAddr = NextRd();
        L($"mul.wide.u32 {outBytes}, {outOffset}, {I(4 * components)};");
        L($"add.u64 {outAddr}, {basePtr[spec.Output.ParameterIndex]}, {outBytes};");

        for (int c = 0; c < components; c++)
        {
            string slot = c == 0 ? $"[{outAddr}]" : $"[{outAddr}+{I(4 * c)}]";
            if (spec.Output.NeedsAtomicStore)
            {
                if (outPred is null) L($"red.global.add.f32 {slot}, {acc[c]};");
                else L($"@{outPred} red.global.add.f32 {slot}, {acc[c]};");
                AtomicStores++;
            }
            else if (outPred is null) L($"st.global.f32 {slot}, {acc[c]};");
            else L($"@{outPred} st.global.f32 {slot}, {acc[c]};");
        }

        _body.Append("END:\n    ret;\n}\n");
        return Assemble();
    }

    /// <summary>
    /// Loads one element as <paramref name="components"/> adjacent fp32 values.
    /// </summary>
    /// <remarks>
    /// The offset arithmetic is shared with the real path, so index maps, bounds predicates
    /// and gather indices behave identically -- an element's components live INSIDE the
    /// element, so a tensor of complex numbers has exactly the shape it declares and none of
    /// the addressing changes. Only the byte scale does.
    /// </remarks>
    private string[] EmitComponentLoad(
        CodegenTensorBinding binding,
        string basePtr,
        string[] axisReg,
        int[] reductionValues,
        int[] reductionAxes,
        int components,
        out string? predicate)
    {
        string offset = EmitOffset(binding, axisReg, reductionValues, reductionAxes, out predicate);
        string bytes = NextRd(), addr = NextRd();
        L($"mul.wide.s32 {bytes}, {offset}, {I(4 * components)};");
        L($"add.u64 {addr}, {basePtr}, {bytes};");

        var values = new string[components];
        for (int c = 0; c < components; c++)
        {
            values[c] = NextF();
            string slot = c == 0 ? $"[{addr}]" : $"[{addr}+{I(4 * c)}]";
            if (predicate is null)
            {
                L($"ld.global.nc.f32 {values[c]}, {slot};");
            }
            else
            {
                L($"mov.f32 {values[c]}, 0f00000000;");
                L($"@{predicate} ld.global.nc.f32 {values[c]}, {slot};");
            }
            EmittedLoads++;
        }
        return values;
    }

    /// <summary>Emits one algebra product from its multiply-accumulate table.</summary>
    private string[] EmitAlgebraMultiply(
        CodegenProductTerm[] table, int components, string[] a, string[] b)
    {
        var result = new string[components];
        var started = new bool[components];

        foreach (var term in table)
        {
            int c = term.Out;
            if (!started[c])
            {
                // The first term of a component is a bare multiply; a negative first term
                // multiplies the negated operand rather than costing a separate negate.
                result[c] = NextF();
                if (term.Sign > 0) L($"mul.rn.f32 {result[c]}, {a[term.A]}, {b[term.B]};");
                else
                {
                    string negated = NextF();
                    L($"neg.f32 {negated}, {a[term.A]};");
                    L($"mul.rn.f32 {result[c]}, {negated}, {b[term.B]};");
                }
                started[c] = true;
            }
            else
            {
                // Every later term is a single fused multiply-add, so a quaternion product
                // is sixteen instructions rather than sixteen multiplies plus twelve adds,
                // and each component carries one rounding per term instead of two.
                string next = NextF();
                if (term.Sign > 0) L($"fma.rn.f32 {next}, {a[term.A]}, {b[term.B]}, {result[c]};");
                else
                {
                    string negated = NextF();
                    L($"neg.f32 {negated}, {a[term.A]};");
                    L($"fma.rn.f32 {next}, {negated}, {b[term.B]}, {result[c]};");
                }
                result[c] = next;
            }
            AlgebraProductTerms++;
        }

        return result;
    }
}
