// Copyright (c) AiDotNet. All rights reserved.
// Lowers a CodegenKernelSpec to SM86 PTX.
//
// This is the generated-code half of the C#-vs-Rust bake-off. It replaces
// hand-written PTX text for conv-class kernels, and it exists to remove a defect
// class rather than to save typing:
//
//   * the launch grid and the in-kernel bounds guard both read
//     CodegenIterationSpace.TotalThreads, so they cannot disagree;
//   * a load's validity predicate is derived from its index map and the tensor
//     shape, so it cannot be forgotten or hand-recomputed wrongly.
//
// Both of those were real failures in the hand-written #841 kernels.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using AiDotNet.Tensors.Engines.Compilation.Codegen.Ir;

namespace AiDotNet.Tensors.Engines.Compilation.Codegen.Ptx;

/// <summary>
/// Emits SM86 PTX for a <see cref="CodegenKernelSpec"/>.
/// </summary>
public sealed class PtxAffineEmitter
{
    /// <summary>Threads per block. Matches the hand-written kernels so metrics compare like-for-like.</summary>
    public const int BlockThreads = 256;

    /// <summary>
    /// Reduction trip counts at or below this are fully unrolled, which folds the
    /// reduction axes into compile-time constants inside every index expression.
    /// That is the specialisation a general library such as cuDNN cannot take,
    /// and it is what turns a guarded gather into a handful of constant-offset loads.
    /// </summary>
    public const int FullUnrollLimit = 64;

    private readonly StringBuilder _sb = new(16384);
    private int _r, _f, _p, _rd;
    private IReadOnlyList<CodegenAxis> axesMeta = Array.Empty<CodegenAxis>();

    private string NextR() => "%r" + (_r++).ToString(CultureInfo.InvariantCulture);
    private string NextF() => "%f" + (_f++).ToString(CultureInfo.InvariantCulture);
    private string NextP() => "%p" + (_p++).ToString(CultureInfo.InvariantCulture);
    private string NextRd() => "%rd" + (_rd++).ToString(CultureInfo.InvariantCulture);
    private static string I(long v) => v.ToString(CultureInfo.InvariantCulture);
    private void L(string line) => _sb.Append("    ").Append(line).Append('\n');

    /// <summary>Number of SASS-visible global loads the emitter produced (diagnostic).</summary>
    public int EmittedLoads { get; private set; }

    /// <summary>True when the reduction was fully unrolled.</summary>
    public bool Unrolled { get; private set; }

    /// <summary>Bounds guards elided because interval analysis proved them unnecessary.</summary>
    public int ElidedGuards { get; private set; }

    /// <summary>
    /// Emits PTX for <paramref name="spec"/>.
    /// </summary>
    /// <exception cref="NotSupportedException">
    /// Thrown for specs this layer deliberately cannot express (data-dependent
    /// indexing). Declining loudly is required -- silently mis-lowering an index
    /// map is exactly the failure this layer exists to prevent.
    /// </exception>
    /// <summary>Number of reduction axes lowered to runtime loops rather than unrolled.</summary>
    public int LoopedAxes { get; private set; }

    public string Emit(CodegenKernelSpec spec, int computeMajor, int computeMinor)
    {
        if (spec is null) throw new ArgumentNullException(nameof(spec));

        var space = spec.Space;
        var axes = space.Axes;
        axesMeta = axes;
        int[] parallel = space.ParallelAxes;
        int[] reduction = space.ReductionAxes;
        long total = space.TotalThreads;           // single source of truth
        long trips = space.ReductionTripCount;

        // STRIP-MINE. Full unroll is the fast path but it cannot be the only path:
        // a dense 3x3 conv over 32 input channels is 288 reduction trips, and
        // unrolling that produces a kernel ptxas cannot allocate. Peel outer
        // reduction axes into runtime loops until the remaining suffix fits the
        // unroll limit, so the inner taps stay unrolled (where the index folding
        // and guard elision pay off) while the channel walk becomes a real loop.
        int split = 0;
        long innerTrips = trips;
        while (innerTrips > FullUnrollLimit && split < reduction.Length)
        {
            innerTrips /= axes[reduction[split]].Extent;
            split++;
        }

        var loopAxes = new int[split];
        Array.Copy(reduction, 0, loopAxes, 0, split);
        var innerAxes = new int[reduction.Length - split];
        Array.Copy(reduction, split, innerAxes, 0, innerAxes.Length);

        Unrolled = split == 0;
        LoopedAxes = split;
        trips = innerTrips;
        reduction = innerAxes;

        _sb.Clear(); _r = _f = _p = _rd = 0; EmittedLoads = 0; ElidedGuards = 0;

        _sb.Append(".version 7.1\n")
           .Append(".target sm_").Append(I(computeMajor)).Append(I(computeMinor)).Append('\n')
           .Append(".address_size 64\n\n")
           .Append("// generated by PtxAffineEmitter from CodegenKernelSpec\n")
           .Append("// ").Append(spec.Describe().Replace("\n", "\n// ")).Append('\n')
           .Append(".visible .entry ").Append(spec.Name).Append("(\n");

        int paramCount = spec.ParameterCount;
        for (int i = 0; i < paramCount; i++)
            _sb.Append("    .param .u64 p").Append(I(i)).Append(i == paramCount - 1 ? "\n" : ",\n");
        _sb.Append(")\n{\n");

        // Generous virtual-register declarations; ptxas performs the real allocation.
        _sb.Append("    .reg .pred %p<").Append(I(256)).Append(">;\n")
           .Append("    .reg .b32 %r<").Append(I(1024)).Append(">;\n")
           .Append("    .reg .b64 %rd<").Append(I(512)).Append(">;\n")
           .Append("    .reg .f32 %f<").Append(I(512)).Append(">;\n");

        // Base pointers.
        var basePtr = new string[paramCount];
        for (int i = 0; i < paramCount; i++)
        {
            basePtr[i] = NextRd();
            L($"ld.param.u64 {basePtr[i]}, [p{I(i)}];");
        }

        // Flat thread id.
        string ctaid = NextR(), tid = NextR(), gid = NextR();
        L($"mov.u32 {ctaid}, %ctaid.x;");
        L($"mov.u32 {tid}, %tid.x;");
        L($"mad.lo.u32 {gid}, {ctaid}, {I(BlockThreads)}, {tid};");

        // Bounds guard derived from the SAME TotalThreads the host launches with.
        string guard = NextP();
        L($"setp.ge.u32 {guard}, {gid}, {I(total)};");
        L($"@{guard} bra END;");

        // Decompose the flat id across parallel axes, last-declared fastest, so
        // consecutive threads walk the contiguous tensor axis.
        var axisReg = new string[axes.Count];
        string rest = gid;
        for (int p = parallel.Length - 1; p >= 0; p--)
        {
            int ax = parallel[p];
            int extent = axes[ax].Extent;
            axisReg[ax] = NextR();
            if (p == 0)
            {
                // Outermost axis takes whatever remains; no divide needed.
                L($"mov.u32 {axisReg[ax]}, {rest};   // {axes[ax].Name}");
            }
            else
            {
                L($"rem.u32 {axisReg[ax]}, {rest}, {I(extent)};   // {axes[ax].Name}");
                string nr = NextR();
                L($"div.u32 {nr}, {rest}, {I(extent)};");
                rest = nr;
            }
        }

        // Accumulator.
        string acc = NextF();
        L(spec.Reduce == CodegenReduceKind.Max
            ? $"mov.f32 {acc}, 0fFF800000;   // -inf"
            : $"mov.f32 {acc}, 0f00000000;");

        // Open one runtime loop per peeled axis. Each level emits its counter reset
        // BEFORE its own label, so the reset for level i+1 lands inside level i's
        // body and re-runs on every outer trip.
        string accFixed = acc;
        var loopRegs = new string[loopAxes.Length];
        for (int i = 0; i < loopAxes.Length; i++)
        {
            string reg = NextR();
            loopRegs[i] = reg;
            axisReg[loopAxes[i]] = reg;   // symbolic from here on, not a folded constant
            L($"mov.u32 {reg}, 0;   // {axes[loopAxes[i]].Name}");
            _sb.Append("LOOP").Append(I(i)).Append(":\n");
        }

        // Reduction over the axes that remain unrolled: every one of those takes a
        // compile-time value, so each index expression folds to (symbolic terms) +
        // constant. A peeled axis stays symbolic and is simply another term.
        var reductionValues = new int[axes.Count];
        for (long t = 0; t < trips; t++)
        {
            long r = t;
            for (int i = reduction.Length - 1; i >= 0; i--)
            {
                int ax = reduction[i];
                int extent = axes[ax].Extent;
                reductionValues[ax] = (int)(r % extent);
                r /= extent;
            }

            string? product = null;
            string? productPred = null;
            foreach (int inputIdx in spec.ProductInputs)
            {
                var binding = spec.Inputs[inputIdx];
                string value = EmitLoad(binding, basePtr[binding.ParameterIndex], axisReg,
                                        reductionValues, reduction, out string? pred);
                if (product is null) { product = value; productPred = pred; }
                else
                {
                    string mul = NextF();
                    L($"mul.rn.f32 {mul}, {product!}, {value};");
                    product = mul;
                    productPred = AndPred(productPred, pred);
                }
            }

            // An out-of-range tap contributes the additive identity; the guarded
            // load already produced 0, so no extra select is needed for Sum.
            if (spec.Reduce == CodegenReduceKind.Max)
            {
                L($"max.f32 {acc}, {acc}, {product!};");
            }
            else
            {
                string na = NextF();
                L($"add.rn.f32 {na}, {acc}, {product!};");
                acc = na;
            }
        }

        // Close the loops. The renamed accumulator must land back in the fixed
        // register before the backward branch: SSA-style renaming cannot cross it.
        if (loopAxes.Length > 0)
        {
            if (!string.Equals(acc, accFixed, StringComparison.Ordinal))
                L($"mov.f32 {accFixed}, {acc};");
            for (int i = loopAxes.Length - 1; i >= 0; i--)
            {
                string cont = NextP();
                L($"add.s32 {loopRegs[i]}, {loopRegs[i]}, 1;");
                L($"setp.lt.s32 {cont}, {loopRegs[i]}, {I(axes[loopAxes[i]].Extent)};");
                L($"@{cont} bra LOOP{I(i)};");
            }
            acc = accFixed;
        }

        // Epilogue: bias, scale, activation -- fused, never a second kernel.
        if (spec.BiasInput.HasValue)
        {
            var b = spec.Inputs[spec.BiasInput.Value];
            string v = EmitLoad(b, basePtr[b.ParameterIndex], axisReg, reductionValues, reduction, out _);
            string na = NextF();
            L($"add.rn.f32 {na}, {acc}, {v};");
            acc = na;
        }
        if (spec.ScaleInput.HasValue)
        {
            var s = spec.Inputs[spec.ScaleInput.Value];
            string v = EmitLoad(s, basePtr[s.ParameterIndex], axisReg, reductionValues, reduction, out _);
            string na = NextF();
            L($"mul.rn.f32 {na}, {acc}, {v};");
            acc = na;
        }
        if (spec.Activation == CodegenActivationKind.ReLU)
            L($"max.f32 {acc}, {acc}, 0f00000000;");

        // Store.
        string outOff = EmitOffset(spec.Output, axisReg, reductionValues, reduction, out string? outPred);
        string outAddr = NextRd(), outByte = NextRd();
        L($"mul.wide.u32 {outByte}, {outOff}, 4;");
        L($"add.u64 {outAddr}, {basePtr[spec.Output.ParameterIndex]}, {outByte};");
        if (outPred is null) L($"st.global.f32 [{outAddr}], {acc};");
        else L($"@{outPred} st.global.f32 [{outAddr}], {acc};");

        _sb.Append("END:\n    ret;\n}\n");
        return _sb.ToString();
    }

    /// <summary>
    /// Emits the flat element offset for a binding, plus the DERIVED validity
    /// predicate (null when the maps provably cannot leave the tensor).
    /// </summary>
    private string EmitOffset(
        CodegenTensorBinding binding,
        string[] axisReg,
        int[] reductionValues,
        int[] reductionAxes,
        out string? predicate)
    {
        predicate = null;
        var reductionSet = new HashSet<int>(reductionAxes);
        string? offset = null;

        for (int d = 0; d < binding.Map.Count; d++)
        {
            var expr = binding.Map[d];
            int dim = binding.Shape[d];
            long stride = binding.Stride(d);

            // Fold every reduction-axis term into the constant; keep parallel terms symbolic.
            int folded = expr.Constant;
            var symbolic = new List<CodegenAffineTerm>();
            foreach (var term in expr.Terms)
            {
                if (reductionSet.Contains(term.Axis)) folded += term.Coefficient * reductionValues[term.Axis];
                else symbolic.Add(term);
            }

            // Build the numerator.
            string? num;
            if (symbolic.Count == 0)
            {
                num = NextR();
                L($"mov.u32 {num}, {I(folded)};");
            }
            else
            {
                num = null;
                foreach (var term in symbolic)
                {
                    string contribution;
                    if (term.Coefficient == 1) contribution = axisReg[term.Axis];
                    else
                    {
                        contribution = NextR();
                        L($"mul.lo.s32 {contribution}, {axisReg[term.Axis]}, {I(term.Coefficient)};");
                    }
                    if (num is null) num = contribution;
                    else { string s = NextR(); L($"add.s32 {s}, {num}, {contribution};"); num = s; }
                }
                if (folded != 0) { string s = NextR(); L($"add.s32 {s}, {num}, {I(folded)};"); num = s; }
            }

            // Apply the divisor, deriving the exactness predicate when required.
            string idx = num!;
            if (expr.Divisor != 1)
            {
                if (expr.RequiresExactDivision)
                {
                    string rem = NextR(), pe = NextP();
                    L($"rem.s32 {rem}, {num}, {I(expr.Divisor)};");
                    L($"setp.eq.s32 {pe}, {rem}, 0;");
                    predicate = AndPred(predicate, pe);
                }
                idx = NextR();
                L($"div.s32 {idx}, {num}, {I(expr.Divisor)};");
            }

            // Derived bounds predicate: 0 <= idx < dim, emitted only when the folded
            // expression can ACTUALLY leave the tensor.
            //
            // Interval analysis over the parallel axis ranges, not a syntactic guess.
            // The syntactic form is both unsound and wasteful: after a reduction axis is
            // folded away, `oh + kh - 1` becomes `oh - 1`, `oh`, or `oh + 1` depending on
            // the tap, and only the first and last can escape [0, H). Testing the
            // pre-folding constant guards all three; testing the folded range guards
            // exactly the two that need it -- fewer instructions AND no missed case.
            long rangeLo = folded, rangeHi = folded;
            foreach (var term in symbolic)
            {
                long span = (long)term.Coefficient * (axesMeta[term.Axis].Extent - 1);
                if (term.Coefficient >= 0) rangeHi += span; else rangeLo += span;
            }
            bool canEscape = expr.Divisor != 1 || rangeLo < 0 || rangeHi >= dim;
            if (!canEscape) ElidedGuards++;
            if (canEscape)
            {
                string lo = NextP(), hi = NextP(), both = NextP();
                L($"setp.ge.s32 {lo}, {idx}, 0;");
                L($"setp.lt.s32 {hi}, {idx}, {I(dim)};");
                L($"and.pred {both}, {lo}, {hi};");
                predicate = AndPred(predicate, both);
            }

            // offset += idx * stride
            if (stride == 1)
            {
                if (offset is null) offset = idx;
                else { string s = NextR(); L($"add.s32 {s}, {offset}, {idx};"); offset = s; }
            }
            else
            {
                string scaled = NextR();
                if (offset is null) { L($"mul.lo.s32 {scaled}, {idx}, {I(stride)};"); offset = scaled; }
                else { L($"mad.lo.s32 {scaled}, {idx}, {I(stride)}, {offset};"); offset = scaled; }
            }
        }

        return offset!;
    }

    /// <summary>Emits a guarded load, yielding 0 for an out-of-range access (zero padding).</summary>
    private string EmitLoad(
        CodegenTensorBinding binding,
        string basePtr,
        string[] axisReg,
        int[] reductionValues,
        int[] reductionAxes,
        out string? predicate)
    {
        string offset = EmitOffset(binding, axisReg, reductionValues, reductionAxes, out predicate);
        string byteOff = NextRd(), addr = NextRd(), dst = NextF();
        L($"mul.wide.s32 {byteOff}, {offset}, 4;");
        L($"add.u64 {addr}, {basePtr}, {byteOff};");
        if (predicate is null)
        {
            L($"ld.global.nc.f32 {dst}, [{addr}];");
        }
        else
        {
            L($"mov.f32 {dst}, 0f00000000;");
            L($"@{predicate} ld.global.nc.f32 {dst}, [{addr}];");
        }
        EmittedLoads++;
        return dst;
    }

    private string? AndPred(string? a, string? b)
    {
        if (a is null) return b;
        if (b is null) return a;
        string c = NextP();
        L($"and.pred {c}, {a}, {b};");
        return c;
    }

    /// <summary>Blocks needed to cover the spec's iteration space at <see cref="BlockThreads"/>.</summary>
    public static uint GridBlocks(CodegenKernelSpec spec)
    {
        if (spec is null) throw new ArgumentNullException(nameof(spec));
        long total = spec.Space.TotalThreads;      // same property the guard uses
        return (uint)((total + BlockThreads - 1) / BlockThreads);
    }
}
