// Copyright (c) AiDotNet. All rights reserved.

using System;
using System.Globalization;
using System.Text;
using AiDotNet.Tensors.Engines.Compilation.Codegen.Ir;

namespace AiDotNet.Tensors.Engines.Compilation.Codegen.Ptx;

/// <summary>Emits a double-buffered FP32 dense 3x3 weight-gradient partial.</summary>
public sealed class PtxTiledConv2DOuterProductEmitter
{
    // PTX ISA 7.5 introduced the ignore-source predicate used by the window cp.async.
    private const string PredicatedAsyncCopyPtxIsaVersion = "7.5";
    private const int ValuesPerCopy = 4;
    private const int BytesPerCopy = ValuesPerCopy * sizeof(float);
    private const int FixedR = 20;
    private const int FixedRd = 8;
    private const int FixedP = 4;
    private readonly StringBuilder _body = new();
    private int _r, _rd, _p, _f;

    public CodegenTiledConv2DOuterProductPlan? Plan { get; private set; }
    public uint LaunchBlocks => checked((uint)(Plan?.Blocks ?? 0));
    public int LaunchBlockThreads => Plan?.BlockThreads ?? 0;
    public int SharedMemoryBytes => Plan?.SharedMemoryBytes ?? 0;

    public string Emit(CodegenKernelSpec spec, int computeMajor, int computeMinor)
    {
        if (computeMajor < 8)
            throw new NotSupportedException(
                "The double-buffered dense weight tile requires cp.async on sm_80+.");
        if (!CodegenTiledConv2DOuterProductPlan.TryCreate(
                spec, out var possible, out string reason))
            throw new NotSupportedException(
                "This spec cannot use the tiled dense weight partial: " + reason);
        var plan = possible!;

        Plan = plan;
        _body.Clear();
        _r = FixedR;
        _rd = FixedRd;
        _p = FixedP;
        _f = 0;

        int directParam = spec.Inputs[plan.DirectInput].ParameterIndex;
        int windowParam = spec.Inputs[plan.WindowInput].ParameterIndex;
        int outputParam = spec.Output.ParameterIndex;
        int tilesM = plan.M / plan.TileM;
        int tilesN = plan.N / plan.TileN;

        L($"ld.param.u64 %rd0, [p{I(directParam)}];");
        L($"ld.param.u64 %rd1, [p{I(windowParam)}];");
        L($"ld.param.u64 %rd2, [p{I(outputParam)}];");
        L("mov.u64 %rd3, stage;");
        L("mov.u32 %r0, %ctaid.x;");
        L("mov.u32 %r1, %tid.x;");
        L($"rem.u32 %r2, %r0, {I(tilesN)};              // C tile");
        L($"div.u32 %r3, %r0, {I(tilesN)};");
        L($"rem.u32 %r4, %r3, {I(tilesM)};              // K tile");
        L($"div.u32 %r5, %r3, {I(tilesM)};");
        L($"rem.u32 %r8, %r5, {I(plan.TapRows)};        // kh");
        L($"div.u32 %r9, %r5, {I(plan.TapRows)};        // promoted row/chunk");
        L($"rem.u32 %r10, %r1, {I(plan.ThreadsN)};      // thread C");
        L($"div.u32 %r11, %r1, {I(plan.ThreadsN)};      // thread K");
        L($"mul.lo.u32 %r12, %r4, {I(plan.TileM)};");
        L($"mul.lo.u32 %r13, %r2, {I(plan.TileN)};");

        var accumulators = new string[
            plan.ThreadTileM, plan.ThreadTileN, plan.TapColumns];
        for (int i = 0; i < plan.ThreadTileM; i++)
            for (int j = 0; j < plan.ThreadTileN; j++)
                for (int kw = 0; kw < plan.TapColumns; kw++)
                {
                    accumulators[i, j, kw] = NextF();
                    L($"mov.f32 {accumulators[i, j, kw]}, 0f00000000;");
                }

        L("mov.u32 %r14, 0;");
        L("mov.u32 %r15, 0;");
        EmitAsyncStage(plan, "%r14", "%r15");
        L("cp.async.commit_group;");
        L("cp.async.wait_group 0;");
        L("bar.sync 0;");
        L("TILED_DW_REDUCE:");
        L("add.u32 %r16, %r14, 1;");
        L($"setp.lt.u32 %p0, %r16, {I(plan.Steps)};");
        L($"xor.b32 %r17, %r15, {I(plan.StageBytes)};");
        L("@!%p0 bra TILED_DW_COMPUTE;");
        EmitAsyncStage(plan, "%r16", "%r17");
        L("cp.async.commit_group;");
        L("TILED_DW_COMPUTE:");
        EmitCompute(plan, "%r15", accumulators);
        L("@!%p0 bra TILED_DW_DONE;");
        L("cp.async.wait_group 0;");
        L("bar.sync 0;");
        L("mov.u32 %r14, %r16;");
        L("mov.u32 %r15, %r17;");
        L("bra TILED_DW_REDUCE;");
        L("TILED_DW_DONE:");

        EmitStores(plan, accumulators);
        L("ret;");

        string isaVersion = computeMajor == 8 && computeMinor < 9
            ? PredicatedAsyncCopyPtxIsaVersion
            : PtxAffineEmitter.PtxIsaVersionFor(computeMajor, computeMinor);
        var text = new StringBuilder();
        text.Append(".version ").Append(isaVersion).Append('\n')
            .Append(".target sm_").Append(I(computeMajor)).Append(I(computeMinor)).Append('\n')
            .Append(".address_size 64\n\n")
            .Append("// generated by PtxTiledConv2DOuterProductEmitter -- true-fp32 SIMT\n")
            .Append("// output tile ").Append(I(plan.TileM)).Append('x').Append(I(plan.TileN))
            .Append(", row ").Append(I(plan.InnerReduction)).Append(", double-buffered\n")
            .Append("// ").Append(spec.Describe().Replace("\n", "\n// ")).Append('\n')
            .Append(".visible .entry ").Append(spec.Name).Append("(\n");
        for (int i = 0; i < spec.ParameterCount; i++)
            text.Append("    .param .u64 p").Append(I(i))
                .Append(i == spec.ParameterCount - 1 ? "\n" : ",\n");
        text.Append(")\n{\n")
            .Append("    .shared .align 16 .b8 stage[").Append(I(plan.SharedMemoryBytes))
            .Append("];\n")
            .Append("    .reg .pred %p<").Append(I(_p + 2)).Append(">;\n")
            .Append("    .reg .b32 %r<").Append(I(_r + 2)).Append(">;\n")
            .Append("    .reg .b64 %rd<").Append(I(_rd + 2)).Append(">;\n")
            .Append("    .reg .f32 %f<").Append(I(_f + 2)).Append(">;\n\n")
            .Append(_body)
            .Append("}\n");
        return text.ToString();
    }

    private void EmitAsyncStage(
        CodegenTiledConv2DOuterProductPlan plan, string step, string bufferBase)
    {
        EmitDirectStage(plan, step, bufferBase);
        EmitWindowStage(plan, step, bufferBase);
    }

    private void EmitDirectStage(
        CodegenTiledConv2DOuterProductPlan plan, string step, string bufferBase)
    {
        int chunksPerRow = plan.InnerReduction / ValuesPerCopy;
        int chunks = plan.TileM * chunksPerRow;
        int passes = (chunks + plan.BlockThreads - 1) / plan.BlockThreads;
        for (int pass = 0; pass < passes; pass++)
        {
            string index = NextR(), localM = NextR(), column = NextR();
            string globalM = NextR(), sourceBatch = NextR(), rowWithin = NextR();
            string sourceRow = NextR(), element = NextR();
            string bytes = NextRd(), source = NextRd(), sharedBytes = NextRd();
            string destination = NextRd();
            string valid = NextP();
            L($"add.u32 {index}, %r1, {I(pass * plan.BlockThreads)};");
            L($"setp.lt.u32 {valid}, {index}, {I(chunks)};");
            L($"div.u32 {localM}, {index}, {I(chunksPerRow)};");
            L($"rem.u32 {column}, {index}, {I(chunksPerRow)};");
            L($"add.u32 {globalM}, {localM}, %r12;");
            L($"div.u32 {sourceBatch}, {step}, {I(plan.RowsPerPartial)};");
            L($"rem.u32 {rowWithin}, {step}, {I(plan.RowsPerPartial)};");
            L($"mad.lo.u32 {sourceRow}, %r9, {I(plan.RowsPerPartial)}, {rowWithin};");
            L($"mad.lo.u32 {element}, {sourceBatch}, {I(plan.M)}, {globalM};");
            L($"mad.lo.u32 {element}, {element}, {I(plan.InputHeight)}, {sourceRow};");
            L($"mul.lo.u32 {element}, {element}, {I(plan.InnerReduction)};");
            L($"mad.lo.u32 {element}, {column}, {I(ValuesPerCopy)}, {element};");
            L($"mul.wide.u32 {bytes}, {element}, 4;");
            L($"add.u64 {source}, %rd0, {bytes};");
            L($"mul.wide.u32 {sharedBytes}, {index}, {I(BytesPerCopy)};");
            L($"add.u64 {destination}, %rd3, {sharedBytes};");
            L($"cvt.u64.u32 {sharedBytes}, {bufferBase};");
            L($"add.u64 {destination}, {destination}, {sharedBytes};");
            L($"@{valid} cp.async.ca.shared.global " +
              $"[{destination}], [{source}], {I(BytesPerCopy)};");
        }
    }

    private void EmitWindowStage(
        CodegenTiledConv2DOuterProductPlan plan, string step, string bufferBase)
    {
        int sharedBase = plan.DirectStageElements * sizeof(float);
        int chunksPerRow = plan.InputWidth / ValuesPerCopy;
        int chunks = plan.TileN * chunksPerRow;
        int passes = (chunks + plan.BlockThreads - 1) / plan.BlockThreads;
        for (int pass = 0; pass < passes; pass++)
        {
            string index = NextR(), localN = NextR(), column = NextR();
            string globalN = NextR(), sourceBatch = NextR(), rowWithin = NextR();
            string sourceRow = NextR(), safeRow = NextR();
            string element = NextR();
            string bytes = NextRd(), source = NextRd(), sharedBytes = NextRd();
            string destination = NextRd();
            string valid = NextP(), below = NextP(), above = NextP(), ignore = NextP();
            L($"add.u32 {index}, %r1, {I(pass * plan.BlockThreads)};");
            L($"setp.lt.u32 {valid}, {index}, {I(chunks)};");
            L($"div.u32 {localN}, {index}, {I(chunksPerRow)};");
            L($"rem.u32 {column}, {index}, {I(chunksPerRow)};");
            L($"add.u32 {globalN}, {localN}, %r13;");
            L($"div.u32 {sourceBatch}, {step}, {I(plan.RowsPerPartial)};");
            L($"rem.u32 {rowWithin}, {step}, {I(plan.RowsPerPartial)};");
            L($"mad.lo.u32 {sourceRow}, %r9, {I(plan.RowsPerPartial)}, {rowWithin};");
            L($"add.s32 {sourceRow}, {sourceRow}, %r8;");
            L($"add.s32 {sourceRow}, {sourceRow}, -1;");
            L($"setp.lt.s32 {below}, {sourceRow}, 0;");
            L($"setp.ge.s32 {above}, {sourceRow}, {I(plan.InputHeight)};");
            L($"or.pred {ignore}, {below}, {above};");
            L($"max.s32 {safeRow}, {sourceRow}, 0;");
            L($"min.s32 {safeRow}, {safeRow}, {I(plan.InputHeight - 1)};");
            L($"mad.lo.u32 {element}, {sourceBatch}, {I(plan.N)}, {globalN};");
            L($"mad.lo.u32 {element}, {element}, {I(plan.InputHeight)}, {safeRow};");
            L($"mul.lo.u32 {element}, {element}, {I(plan.InputWidth)};");
            L($"mad.lo.u32 {element}, {column}, {I(ValuesPerCopy)}, {element};");
            L($"mul.wide.u32 {bytes}, {element}, 4;");
            L($"add.u64 {source}, %rd1, {bytes};");
            L($"mul.wide.u32 {sharedBytes}, {index}, {I(BytesPerCopy)};");
            L($"add.u64 {destination}, %rd3, {sharedBytes};");
            L($"cvt.u64.u32 {sharedBytes}, {bufferBase};");
            L($"add.u64 {destination}, {destination}, {sharedBytes};");
            L($"@{valid} cp.async.ca.shared.global " +
              $"[{destination}+{I(sharedBase)}], [{source}], {I(BytesPerCopy)}, {ignore};");
        }
    }

    private void EmitCompute(
        CodegenTiledConv2DOuterProductPlan plan,
        string bufferBase,
        string[,,] accumulators)
    {
        // The operand tiles are thread-stationary for the complete reduction step.
        // Form each dynamic shared-memory base once so the hot loop contains only
        // immediate-offset loads and FP32 FMAs, rather than one address chain per load.
        string leftOffset = NextR(), rightOffset = NextR();
        string leftOffset64 = NextRd(), rightOffset64 = NextRd();
        string leftBase = NextRd(), rightBase = NextRd();
        L($"mad.lo.u32 {leftOffset}, %r11, " +
          $"{I(plan.ThreadTileM * plan.InnerReduction * sizeof(float))}, {bufferBase};");
        L($"mad.lo.u32 {rightOffset}, %r10, " +
          $"{I(plan.ThreadTileN * plan.InputWidth * sizeof(float))}, {bufferBase};");
        L($"add.u32 {rightOffset}, {rightOffset}, " +
          $"{I(plan.DirectStageElements * sizeof(float))};");
        L($"cvt.u64.u32 {leftOffset64}, {leftOffset};");
        L($"cvt.u64.u32 {rightOffset64}, {rightOffset};");
        L($"add.u64 {leftBase}, %rd3, {leftOffset64};");
        L($"add.u64 {rightBase}, %rd3, {rightOffset64};");

        for (int r = 0; r < plan.InnerReduction; r++)
        {
            var left = new string[plan.ThreadTileM];
            var right = new string[plan.ThreadTileN, plan.TapColumns];
            for (int i = 0; i < left.Length; i++)
            {
                left[i] = NextF();
                int offset = (i * plan.InnerReduction + r) * sizeof(float);
                L($"ld.shared.f32 {left[i]}, [{leftBase}+{I(offset)}];");
            }
            for (int j = 0; j < plan.ThreadTileN; j++)
                for (int kw = 0; kw < plan.TapColumns; kw++)
                {
                    right[j, kw] = NextF();
                    int sourceColumn = r + kw - 1;
                    if (sourceColumn < 0 || sourceColumn >= plan.InputWidth)
                    {
                        L($"mov.f32 {right[j, kw]}, 0f00000000;");
                        continue;
                    }

                    int offset = (j * plan.InputWidth + sourceColumn) * sizeof(float);
                    L($"ld.shared.f32 {right[j, kw]}, [{rightBase}+{I(offset)}];");
                }
            for (int i = 0; i < left.Length; i++)
                for (int j = 0; j < plan.ThreadTileN; j++)
                    for (int kw = 0; kw < plan.TapColumns; kw++)
                        L($"fma.rn.f32 {accumulators[i, j, kw]}, {left[i]}, {right[j, kw]}, " +
                          $"{accumulators[i, j, kw]};");
        }
    }

    private void EmitStores(
        CodegenTiledConv2DOuterProductPlan plan, string[,,] accumulators)
    {
        for (int i = 0; i < plan.ThreadTileM; i++)
            for (int j = 0; j < plan.ThreadTileN; j++)
                for (int kw = 0; kw < plan.TapColumns; kw++)
                {
                string localM = NextR(), localN = NextR();
                string globalM = NextR(), globalN = NextR(), element = NextR();
                string bytes = NextRd(), address = NextRd();
                L($"mad.lo.u32 {localM}, %r11, {I(plan.ThreadTileM)}, {I(i)};");
                L($"mad.lo.u32 {localN}, %r10, {I(plan.ThreadTileN)}, {I(j)};");
                L($"add.u32 {globalM}, %r12, {localM};");
                L($"add.u32 {globalN}, %r13, {localN};");
                L($"mad.lo.u32 {element}, {globalM}, {I(plan.N)}, {globalN};");
                L($"mad.lo.u32 {element}, {element}, {I(plan.TapRows)}, %r8;");
                L($"mad.lo.u32 {element}, {element}, {I(plan.TapColumns)}, {I(kw)};");
                L($"mad.lo.u32 {element}, {element}, {I(plan.Batch)}, %r9;");
                L($"mul.wide.u32 {bytes}, {element}, 4;");
                L($"add.u64 {address}, %rd2, {bytes};");
                L($"st.global.f32 [{address}], {accumulators[i, j, kw]};");
                }
    }

    private string NextR() => "%r" + I(_r++);
    private string NextRd() => "%rd" + I(_rd++);
    private string NextP() => "%p" + I(_p++);
    private string NextF() => "%f" + I(_f++);
    private void L(string line) => _body.Append("    ").Append(line).Append('\n');
    private static string I(int value) => value.ToString(CultureInfo.InvariantCulture);
}
