// Copyright (c) AiDotNet. All rights reserved.

using System;
using System.Globalization;
using System.Text;
using AiDotNet.Tensors.Engines.Compilation.Codegen.Ir;

namespace AiDotNet.Tensors.Engines.Compilation.Codegen.Ptx;

/// <summary>Emits a cooperative, double-buffered, true-FP32 dense 3x3 row tile.</summary>
public sealed class PtxTiledConv2DEmitter
{
    private const int FixedR = 16;
    private const int FixedRd = 8;
    private const int FixedP = 4;
    private readonly StringBuilder _body = new();
    private int _r, _rd, _p, _f;

    public CodegenTiledConv2DPlan? Plan { get; private set; }
    public uint LaunchBlocks => checked((uint)(Plan?.Blocks ?? 0));
    public int LaunchBlockThreads => Plan?.BlockThreads ?? 0;
    public int SharedMemoryBytes => Plan?.SharedMemoryBytes ?? 0;

    public string Emit(CodegenKernelSpec spec, int computeMajor, int computeMinor)
    {
        if (computeMajor < 8)
            throw new NotSupportedException("The double-buffered dense-convolution tile requires cp.async on sm_80+.");
        if (!CodegenTiledConv2DPlan.TryCreate(spec, out var possible, out string reason))
            throw new NotSupportedException("This spec cannot use the tiled dense convolution: " + reason);
        var plan = possible!;

        Plan = plan;
        _body.Clear();
        _r = FixedR;
        _rd = FixedRd;
        _p = FixedP;
        _f = 0;

        int matrixParam = spec.Inputs[plan.MatrixInput].ParameterIndex;
        int streamParam = spec.Inputs[plan.StreamInput].ParameterIndex;
        int outputParam = spec.Output.ParameterIndex;
        int tilesM = plan.M / plan.TileM;

        L($"ld.param.u64 %rd0, [p{I(matrixParam)}];");
        L($"ld.param.u64 %rd1, [p{I(streamParam)}];");
        L($"ld.param.u64 %rd2, [p{I(outputParam)}];");
        L("mov.u64 %rd3, stage;");
        if (plan.BiasInput.HasValue)
        {
            int biasParam = spec.Inputs[plan.BiasInput.Value].ParameterIndex;
            L($"ld.param.u64 %rd4, [p{I(biasParam)}];");
        }
        L("mov.u32 %r0, %ctaid.x;");
        L("mov.u32 %r1, %tid.x;");
        L($"rem.u32 %r2, %r0, {I(tilesM)};             // M tile");
        L($"div.u32 %r3, %r0, {I(tilesM)};");
        L($"rem.u32 %r4, %r3, {I(plan.OutputHeight)};  // output row");
        L($"div.u32 %r5, %r3, {I(plan.OutputHeight)};  // batch");
        L($"rem.u32 %r6, %r1, {I(plan.ThreadsWidth)};  // thread column");
        L($"div.u32 %r7, %r1, {I(plan.ThreadsWidth)};  // thread M");
        L($"mul.lo.u32 %r8, %r2, {I(plan.TileM)};      // M origin");

        var accumulators = new string[plan.ThreadTileM, plan.ThreadTileWidth];
        for (int i = 0; i < plan.ThreadTileM; i++)
            for (int j = 0; j < plan.ThreadTileWidth; j++)
            {
                accumulators[i, j] = NextF();
                L($"mov.f32 {accumulators[i, j]}, 0f00000000;");
            }

        // r9 is the current channel step, r10 its shared-buffer byte offset.
        // r11/r12 hold the next step/buffer, and p0 is a uniform has-next predicate.
        L("mov.u32 %r9, 0;");
        L("mov.u32 %r10, 0;");
        EmitAsyncStage(plan, "%r9", "%r10");
        L("cp.async.commit_group;");
        L("cp.async.wait_group 0;");
        L("bar.sync 0;");
        L("TILED_CONV_REDUCE:");
        L("add.u32 %r11, %r9, 1;");
        L($"setp.lt.u32 %p0, %r11, {I(plan.Steps)};");
        L($"xor.b32 %r12, %r10, {I(plan.StageBytes)};");
        L("@!%p0 bra TILED_CONV_COMPUTE;");
        EmitAsyncStage(plan, "%r11", "%r12");
        L("cp.async.commit_group;");
        L("TILED_CONV_COMPUTE:");
        EmitCompute(plan, "%r10", accumulators);
        L("@!%p0 bra TILED_CONV_DONE;");
        L("cp.async.wait_group 0;");
        L("bar.sync 0;");
        L("mov.u32 %r9, %r11;");
        L("mov.u32 %r10, %r12;");
        L("bra TILED_CONV_REDUCE;");
        L("TILED_CONV_DONE:");

        EmitStores(plan, spec.Activation, accumulators);
        L("ret;");

        var text = new StringBuilder();
        // The ignore-source predicate on cp.async was added in PTX ISA 7.5.
        // Ampere targets otherwise inherit the affine emitter's historical 7.1 floor.
        string isaVersion = computeMajor == 8 && computeMinor < 9
            ? "7.5"
            : PtxAffineEmitter.PtxIsaVersionFor(computeMajor, computeMinor);
        text.Append(".version ").Append(isaVersion).Append('\n')
            .Append(".target sm_").Append(I(computeMajor)).Append(I(computeMinor)).Append('\n')
            .Append(".address_size 64\n\n")
            .Append("// generated by PtxTiledConv2DEmitter -- true-fp32 SIMT\n")
            .Append("// row tile ").Append(I(plan.TileM)).Append('x')
            .Append(I(plan.OutputWidth)).Append(", channels ").Append(I(plan.TileChannels))
            .Append(", double-buffered\n")
            .Append("// ").Append(spec.Describe().Replace("\n", "\n// ")).Append('\n')
            .Append(".visible .entry ").Append(spec.Name).Append("(\n");
        for (int i = 0; i < spec.ParameterCount; i++)
            text.Append("    .param .u64 p").Append(I(i))
                .Append(i == spec.ParameterCount - 1 ? "\n" : ",\n");
        text.Append(")\n{\n")
            .Append("    .shared .align 16 .b8 stage[").Append(I(plan.SharedMemoryBytes))
            .Append("];\n")
            .Append("    .reg .pred %p<").Append(I(_p + 2)).Append(">;\n")
            .Append("    .reg .b32 %r<").Append(I(_r + 2)).Append(">;\n")
            .Append("    .reg .b64 %rd<").Append(I(_rd + 2)).Append(">;\n")
            .Append("    .reg .f32 %f<").Append(I(_f + 2)).Append(">;\n\n")
            .Append(_body)
            .Append("}\n");
        return text.ToString();
    }

    private void EmitAsyncStage(
        CodegenTiledConv2DPlan plan, string step, string bufferBase)
    {
        const int ValuesPerCopy = 4;
        int streamBase = plan.MatrixStageElements * sizeof(float);

        // The physical matrices are [M,C,tap] or [C,M,tap], neither of which places
        // adjacent M values together. Stage a transposed [C,tap,M] tile with scalar
        // asynchronous copies. The extra copy instructions are paid once per CTA and
        // let every compute thread replace two hot shared loads with one aligned v2 load.
        int matrixElements = plan.MatrixStageElements;
        int matrixPasses = (matrixElements + plan.BlockThreads - 1) / plan.BlockThreads;
        for (int pass = 0; pass < matrixPasses; pass++)
        {
            string index = NextR(), localChannel = NextR(), inner = NextR();
            string tap = NextR(), localM = NextR(), globalChannel = NextR();
            string globalM = NextR(), element = NextR(), destinationElement = NextR();
            string bytes = NextRd(), source = NextRd(), sharedBytes = NextRd(), destination = NextRd();
            string valid = NextP();
            L($"add.u32 {index}, %r1, {I(pass * plan.BlockThreads)};");
            L($"setp.lt.u32 {valid}, {index}, {I(matrixElements)};");
            // Assign lanes in physical source order so each warp reads contiguous
            // weights, then transpose only the shared destination to [C,tap,M].
            if (plan.MatrixReductionMajor)
            {
                L($"div.u32 {localChannel}, {index}, {I(9 * plan.TileM)};");
                L($"rem.u32 {inner}, {index}, {I(9 * plan.TileM)};");
                L($"div.u32 {localM}, {inner}, 9;");
                L($"rem.u32 {tap}, {inner}, 9;");
            }
            else
            {
                L($"div.u32 {localM}, {index}, {I(9 * plan.TileChannels)};");
                L($"rem.u32 {inner}, {index}, {I(9 * plan.TileChannels)};");
                L($"div.u32 {localChannel}, {inner}, 9;");
                L($"rem.u32 {tap}, {inner}, 9;");
            }
            L($"mad.lo.u32 {globalChannel}, {step}, {I(plan.TileChannels)}, {localChannel};");
            L($"add.u32 {globalM}, {localM}, %r8;");
            if (plan.MatrixReductionMajor)
            {
                L($"mad.lo.u32 {element}, {globalChannel}, {I(plan.M)}, {globalM};");
            }
            else
            {
                L($"mad.lo.u32 {element}, {globalM}, {I(plan.ReductionChannels)}, {globalChannel};");
            }
            L($"mad.lo.u32 {element}, {element}, 9, {tap};");
            L($"mul.wide.u32 {bytes}, {element}, 4;");
            L($"add.u64 {source}, %rd0, {bytes};");
            L($"mad.lo.u32 {destinationElement}, {localChannel}, 9, {tap};");
            L($"mad.lo.u32 {destinationElement}, {destinationElement}, {I(plan.TileM)}, {localM};");
            L($"mul.wide.u32 {sharedBytes}, {destinationElement}, 4;");
            L($"add.u64 {destination}, %rd3, {sharedBytes};");
            L($"cvt.u64.u32 {sharedBytes}, {bufferBase};");
            L($"add.u64 {destination}, {destination}, {sharedBytes};");
            L($"@{valid} cp.async.ca.shared.global [{destination}], [{source}], 4;");
        }

        int chunksPerInputRow = plan.InputWidth / ValuesPerCopy;
        int inputChunks = plan.StreamStageElements / ValuesPerCopy;
        int inputPasses = (inputChunks + plan.BlockThreads - 1) / plan.BlockThreads;
        for (int pass = 0; pass < inputPasses; pass++)
        {
            string index = NextR(), row = NextR(), column = NextR();
            string localChannel = NextR(), tapRow = NextR(), globalChannel = NextR();
            string sourceRow = NextR(), safeRow = NextR(), element = NextR();
            string bytes = NextRd(), source = NextRd(), sharedBytes = NextRd(), destination = NextRd();
            string valid = NextP(), below = NextP(), above = NextP(), ignore = NextP();
            L($"add.u32 {index}, %r1, {I(pass * plan.BlockThreads)};");
            L($"setp.lt.u32 {valid}, {index}, {I(inputChunks)};");
            L($"div.u32 {row}, {index}, {I(chunksPerInputRow)};");
            L($"rem.u32 {column}, {index}, {I(chunksPerInputRow)};");
            L($"div.u32 {localChannel}, {row}, {I(plan.TapRows)};");
            L($"rem.u32 {tapRow}, {row}, {I(plan.TapRows)};");
            L($"mad.lo.u32 {globalChannel}, {step}, {I(plan.TileChannels)}, {localChannel};");
            L($"mad.lo.s32 {sourceRow}, {tapRow}, {I(plan.TapSign)}, %r4;");
            L($"add.s32 {sourceRow}, {sourceRow}, {I(plan.WindowConstant)};");
            L($"setp.lt.s32 {below}, {sourceRow}, 0;");
            L($"setp.ge.s32 {above}, {sourceRow}, {I(plan.InputHeight)};");
            L($"or.pred {ignore}, {below}, {above};");
            L($"max.s32 {safeRow}, {sourceRow}, 0;");
            L($"min.s32 {safeRow}, {safeRow}, {I(plan.InputHeight - 1)};");
            L($"mad.lo.u32 {element}, %r5, {I(plan.ReductionChannels)}, {globalChannel};");
            L($"mad.lo.u32 {element}, {element}, {I(plan.InputHeight)}, {safeRow};");
            L($"mul.lo.u32 {element}, {element}, {I(plan.InputWidth)};");
            L($"mad.lo.u32 {element}, {column}, {I(ValuesPerCopy)}, {element};");
            L($"mul.wide.u32 {bytes}, {element}, 4;");
            L($"add.u64 {source}, %rd1, {bytes};");
            L($"mul.wide.u32 {sharedBytes}, {index}, 16;");
            L($"add.u64 {destination}, %rd3, {sharedBytes};");
            L($"cvt.u64.u32 {sharedBytes}, {bufferBase};");
            L($"add.u64 {destination}, {destination}, {sharedBytes};");
            L($"@{valid} cp.async.ca.shared.global [{destination}+{I(streamBase)}], [{source}], 16, {ignore};");
        }
    }

    private void EmitCompute(
        CodegenTiledConv2DPlan plan, string bufferBase, string[,] accumulators)
    {
        const int matrixBase = 0;
        int streamBase = plan.MatrixStageElements * sizeof(float);
        for (int c = 0; c < plan.TileChannels; c++)
            for (int kh = 0; kh < plan.TapRows; kh++)
            {
                // Four adjacent outputs across all three column taps need only the six
                // activation values [ow-1, ow..ow+3, ow+4]. Load that window once per
                // channel/input-row and reuse overlapping values for every tap.
                var streamWindow = new string[plan.ThreadTileWidth + 2];
                int rowBase = (c * plan.TapRows + kh) * plan.InputWidth;
                streamWindow[0] = EmitScalarStream(
                    plan, bufferBase, streamBase, rowBase, columnConstant: -1);
                for (int j = 0; j < plan.ThreadTileWidth; j++)
                    streamWindow[j + 1] = NextF();
                {
                    string local = NextR(), local64 = NextRd(), address = NextRd();
                    L($"mad.lo.u32 {local}, %r6, {I(plan.ThreadTileWidth * sizeof(float))}, " +
                      $"{I(streamBase + rowBase * sizeof(float))};");
                    L($"add.u32 {local}, {local}, {bufferBase};");
                    L($"cvt.u64.u32 {local64}, {local};");
                    L($"add.u64 {address}, %rd3, {local64};");
                    L($"ld.shared.v4.f32 {{{streamWindow[1]}, {streamWindow[2]}, " +
                      $"{streamWindow[3]}, {streamWindow[4]}}}, [{address}];");
                }
                streamWindow[^1] = EmitScalarStream(
                    plan, bufferBase, streamBase, rowBase,
                    columnConstant: plan.ThreadTileWidth);

                for (int kw = 0; kw < plan.TapColumns; kw++)
                {
                    var matrix = new string[plan.ThreadTileM];
                    int tap = kh * plan.TapColumns + kw;
                    if (matrix.Length == 2)
                    {
                        matrix[0] = NextF();
                        matrix[1] = NextF();
                        int constant = matrixBase +
                            (c * 9 + tap) * plan.TileM * sizeof(float);
                        string local = NextR(), local64 = NextRd(), address = NextRd();
                        L($"mad.lo.u32 {local}, %r7, {I(plan.ThreadTileM * sizeof(float))}, {I(constant)};");
                        L($"add.u32 {local}, {local}, {bufferBase};");
                        L($"cvt.u64.u32 {local64}, {local};");
                        L($"add.u64 {address}, %rd3, {local64};");
                        L($"ld.shared.v2.f32 {{{matrix[0]}, {matrix[1]}}}, [{address}];");
                    }
                    else
                    {
                        for (int i = 0; i < matrix.Length; i++)
                        {
                            matrix[i] = NextF();
                            int constant = matrixBase +
                                ((c * 9 + tap) * plan.TileM + i) * sizeof(float);
                            string local = NextR(), local64 = NextRd(), address = NextRd();
                            L($"mad.lo.u32 {local}, %r7, {I(plan.ThreadTileM * sizeof(float))}, {I(constant)};");
                            L($"add.u32 {local}, {local}, {bufferBase};");
                            L($"cvt.u64.u32 {local64}, {local};");
                            L($"add.u64 {address}, %rd3, {local64};");
                            L($"ld.shared.f32 {matrix[i]}, [{address}];");
                        }
                    }
                    for (int i = 0; i < matrix.Length; i++)
                        for (int j = 0; j < plan.ThreadTileWidth; j++)
                        {
                            int windowIndex = j + (plan.TapSign == 1
                                ? kw
                                : plan.TapColumns - 1 - kw);
                            L($"fma.rn.f32 {accumulators[i, j]}, {matrix[i]}, " +
                              $"{streamWindow[windowIndex]}, {accumulators[i, j]};");
                        }
                }
            }
    }

    private string EmitScalarStream(
        CodegenTiledConv2DPlan plan, string bufferBase,
        int streamBase, int rowBase, int columnConstant)
    {
        string sourceColumn = NextR(), safeColumn = NextR(), local = NextR();
        string local64 = NextRd(), address = NextRd();
        string inRangeLow = NextP(), inRangeHigh = NextP(), inRange = NextP();
        string loaded = NextF(), result = NextF();
        L($"mad.lo.s32 {sourceColumn}, %r6, {I(plan.ThreadTileWidth)}, {I(columnConstant)};");
        L($"setp.ge.s32 {inRangeLow}, {sourceColumn}, 0;");
        L($"setp.lt.s32 {inRangeHigh}, {sourceColumn}, {I(plan.InputWidth)};");
        L($"and.pred {inRange}, {inRangeLow}, {inRangeHigh};");
        L($"max.s32 {safeColumn}, {sourceColumn}, 0;");
        L($"min.s32 {safeColumn}, {safeColumn}, {I(plan.InputWidth - 1)};");
        L($"mad.lo.u32 {local}, {safeColumn}, 4, " +
          $"{I(streamBase + rowBase * sizeof(float))};");
        L($"add.u32 {local}, {local}, {bufferBase};");
        L($"cvt.u64.u32 {local64}, {local};");
        L($"add.u64 {address}, %rd3, {local64};");
        L($"ld.shared.f32 {loaded}, [{address}];");
        L($"selp.f32 {result}, {loaded}, 0f00000000, {inRange};");
        return result;
    }

    private void EmitStores(
        CodegenTiledConv2DPlan plan, CodegenActivationKind activation,
        string[,] accumulators)
    {
        for (int i = 0; i < plan.ThreadTileM; i++)
        {
            string? bias = null;
            if (plan.BiasInput.HasValue)
            {
                string localM = NextR(), globalM = NextR();
                string biasBytes = NextRd(), biasAddress = NextRd();
                bias = NextF();
                L($"mad.lo.u32 {localM}, %r7, {I(plan.ThreadTileM)}, {I(i)};");
                L($"add.u32 {globalM}, %r8, {localM};");
                L($"mul.wide.u32 {biasBytes}, {globalM}, 4;");
                L($"add.u64 {biasAddress}, %rd4, {biasBytes};");
                L($"ld.global.f32 {bias}, [{biasAddress}];");
            }
            for (int j = 0; j < plan.ThreadTileWidth; j++)
            {
                string localM = NextR(), column = NextR(), globalM = NextR(), element = NextR();
                string bytes = NextRd(), address = NextRd();
                if (bias is not null)
                    L($"add.rn.f32 {accumulators[i, j]}, {accumulators[i, j]}, {bias};");
                if (activation == CodegenActivationKind.ReLU)
                    L($"max.f32 {accumulators[i, j]}, {accumulators[i, j]}, 0f00000000;");
                L($"mad.lo.u32 {localM}, %r7, {I(plan.ThreadTileM)}, {I(i)};");
                L($"mad.lo.u32 {column}, %r6, {I(plan.ThreadTileWidth)}, {I(j)};");
                L($"add.u32 {globalM}, %r8, {localM};");
                L($"mad.lo.u32 {element}, %r5, {I(plan.M)}, {globalM};");
                L($"mad.lo.u32 {element}, {element}, {I(plan.OutputHeight)}, %r4;");
                L($"mad.lo.u32 {element}, {element}, {I(plan.OutputWidth)}, {column};");
                L($"mul.wide.u32 {bytes}, {element}, 4;");
                L($"add.u64 {address}, %rd2, {bytes};");
                L($"st.global.f32 [{address}], {accumulators[i, j]};");
            }
        }
    }

    private string NextR() => "%r" + I(_r++);
    private string NextRd() => "%rd" + I(_rd++);
    private string NextP() => "%p" + I(_p++);
    private string NextF() => "%f" + I(_f++);
    private void L(string line) => _body.Append("    ").Append(line).Append('\n');
    private static string I(int value) => value.ToString(CultureInfo.InvariantCulture);
}
