// Copyright (c) AiDotNet. All rights reserved.

using System;
using System.Globalization;
using System.Text;
using AiDotNet.Tensors.Engines.Compilation.Codegen.Ir;

namespace AiDotNet.Tensors.Engines.Compilation.Codegen.Ptx;

/// <summary>Emits a double-buffered true-FP32 split weight-gradient partial.</summary>
public sealed class PtxTiledOuterProductEmitter
{
    private const int FixedR = 16;
    private const int FixedRd = 8;
    private const int FixedP = 4;
    private readonly StringBuilder _body = new();
    private readonly CodegenTiledOuterProductSchedule _schedule;
    private int _r, _rd, _p, _f;

    public CodegenTiledOuterProductPlan? Plan { get; private set; }
    public uint LaunchBlocks => checked((uint)(Plan?.Blocks ?? 0));
    public int LaunchBlockThreads => Plan?.BlockThreads ?? 0;
    public int SharedMemoryBytes => Plan?.SharedMemoryBytes ?? 0;

    public PtxTiledOuterProductEmitter()
        : this(CodegenTiledOuterProductSchedule.Default)
    {
    }

    public PtxTiledOuterProductEmitter(CodegenTiledOuterProductSchedule schedule) =>
        _schedule = schedule ?? throw new ArgumentNullException(nameof(schedule));

    public string Emit(CodegenKernelSpec spec, int computeMajor, int computeMinor)
    {
        if (computeMajor < 8)
            throw new NotSupportedException("The double-buffered outer product requires cp.async on sm_80+.");
        if (!CodegenTiledOuterProductPlan.TryCreate(
                spec, _schedule, out var possible, out string reason))
            throw new NotSupportedException("This spec cannot use the tiled outer product: " + reason);
        var plan = possible!;

        Plan = plan;
        _body.Clear();
        _r = FixedR;
        _rd = FixedRd;
        _p = FixedP;
        _f = 0;

        int leftParam = spec.Inputs[plan.LeftInput].ParameterIndex;
        int rightParam = spec.Inputs[plan.RightInput].ParameterIndex;
        int outputParam = spec.Output.ParameterIndex;
        int tilesM = plan.M / plan.TileM;
        int tilesN = plan.N / plan.TileN;

        L($"ld.param.u64 %rd0, [p{I(leftParam)}];");
        L($"ld.param.u64 %rd1, [p{I(rightParam)}];");
        L($"ld.param.u64 %rd2, [p{I(outputParam)}];");
        L("mov.u64 %rd3, stage;");
        L("mov.u32 %r0, %ctaid.x;");
        L("mov.u32 %r1, %tid.x;");
        L($"rem.u32 %r2, %r0, {I(tilesN)};             // N tile");
        L($"div.u32 %r3, %r0, {I(tilesN)};");
        L($"rem.u32 %r4, %r3, {I(tilesM)};             // M tile");
        L($"div.u32 %r5, %r3, {I(tilesM)};             // promoted batch axis");
        L($"rem.u32 %r6, %r1, {I(plan.ThreadsN)};       // thread N");
        L($"div.u32 %r7, %r1, {I(plan.ThreadsN)};       // thread M");
        L($"mul.lo.u32 %r8, %r4, {I(plan.TileM)};");
        L($"mul.lo.u32 %r9, %r2, {I(plan.TileN)};");

        var accumulators = new string[plan.ThreadTileM, plan.ThreadTileN];
        for (int i = 0; i < plan.ThreadTileM; i++)
            for (int j = 0; j < plan.ThreadTileN; j++)
            {
                accumulators[i, j] = NextF();
                L($"mov.f32 {accumulators[i, j]}, 0f00000000;");
            }

        EmitAsyncStage(plan, step: 0, buffer: 0);
        L("cp.async.commit_group;");
        L("cp.async.wait_group 0;");
        L("bar.sync 0;");

        for (int step = 0; step < plan.Steps; step++)
        {
            int current = step & 1;
            if (step + 1 < plan.Steps)
            {
                EmitAsyncStage(plan, step + 1, 1 - current);
                L("cp.async.commit_group;");
            }
            EmitCompute(plan, current, accumulators);
            if (step + 1 < plan.Steps)
            {
                L("cp.async.wait_group 0;");
                L("bar.sync 0;");
            }
        }

        EmitStores(plan, accumulators);
        L("ret;");

        var text = new StringBuilder();
        text.Append(".version ")
            .Append(PtxAffineEmitter.PtxIsaVersionFor(computeMajor, computeMinor)).Append('\n')
            .Append(".target sm_").Append(I(computeMajor)).Append(I(computeMinor)).Append('\n')
            .Append(".address_size 64\n\n")
            .Append("// generated by PtxTiledOuterProductEmitter -- true-fp32 SIMT\n")
            .Append("// output tile ").Append(I(plan.TileM)).Append('x').Append(I(plan.TileN))
            .Append(", contiguous reduction row ").Append(I(plan.InnerReduction))
            .Append(", double-buffered\n")
            .Append("// ").Append(spec.Describe().Replace("\n", "\n// ")).Append('\n')
            .Append(".visible .entry ").Append(spec.Name).Append("(\n");
        for (int i = 0; i < spec.ParameterCount; i++)
            text.Append("    .param .u64 p").Append(I(i))
                .Append(i == spec.ParameterCount - 1 ? "\n" : ",\n");
        text.Append(")\n{\n")
            .Append("    .shared .align 16 .b8 stage[").Append(I(plan.SharedMemoryBytes))
            .Append("];\n")
            .Append("    .reg .pred %p<").Append(I(_p + 2)).Append(">;\n")
            .Append("    .reg .b32 %r<").Append(I(_r + 2)).Append(">;\n")
            .Append("    .reg .b64 %rd<").Append(I(_rd + 2)).Append(">;\n")
            .Append("    .reg .f32 %f<").Append(I(_f + 2)).Append(">;\n\n")
            .Append(_body)
            .Append("}\n");
        return text.ToString();
    }

    private void EmitAsyncStage(CodegenTiledOuterProductPlan plan, int step, int buffer)
    {
        int leftBase = buffer * plan.StageBytes;
        int rightBase = leftBase + plan.TileM * plan.InnerReduction * sizeof(float);
        EmitOperandStage(plan, step, plan.M, plan.TileM, "%r8", "%rd0", leftBase);
        EmitOperandStage(plan, step, plan.N, plan.TileN, "%r9", "%rd1", rightBase);
    }

    private void EmitOperandStage(
        CodegenTiledOuterProductPlan plan, int step, int channels, int tileChannels,
        string channelOrigin, string basePointer, int sharedBase)
    {
        const int ValuesPerCopy = 4;
        int chunksPerRow = plan.InnerReduction / ValuesPerCopy;
        int chunks = tileChannels * chunksPerRow;
        int passes = (chunks + plan.BlockThreads - 1) / plan.BlockThreads;
        for (int pass = 0; pass < passes; pass++)
        {
            string index = NextR(), row = NextR(), column = NextR();
            string channel = NextR(), element = NextR();
            string bytes = NextRd(), source = NextRd(), sharedBytes = NextRd(), destination = NextRd();
            string valid = NextP();
            L($"add.u32 {index}, %r1, {I(pass * plan.BlockThreads)};");
            L($"setp.lt.u32 {valid}, {index}, {I(chunks)};");
            L($"div.u32 {row}, {index}, {I(chunksPerRow)};");
            L($"rem.u32 {column}, {index}, {I(chunksPerRow)};");
            L($"add.u32 {channel}, {row}, {channelOrigin};");
            L($"mad.lo.u32 {element}, {I(step)}, {I(channels)}, {channel};");
            L($"mad.lo.u32 {element}, {element}, {I(plan.Batch)}, %r5;");
            L($"mul.lo.u32 {element}, {element}, {I(plan.InnerReduction)};");
            L($"mad.lo.u32 {element}, {column}, {I(ValuesPerCopy)}, {element};");
            L($"mul.wide.u32 {bytes}, {element}, 4;");
            L($"add.u64 {source}, {basePointer}, {bytes};");
            L($"mul.wide.u32 {sharedBytes}, {index}, 16;");
            L($"add.u64 {destination}, %rd3, {sharedBytes};");
            L($"@{valid} cp.async.ca.shared.global [{destination}+{I(sharedBase)}], [{source}], 16;");
        }
    }

    private void EmitCompute(
        CodegenTiledOuterProductPlan plan, int buffer, string[,] accumulators)
    {
        int leftBase = buffer * plan.StageBytes;
        int rightBase = leftBase + plan.TileM * plan.InnerReduction * sizeof(float);
        for (int r = 0; r < plan.InnerReduction; r++)
        {
            var left = new string[plan.ThreadTileM];
            var right = new string[plan.ThreadTileN];
            for (int i = 0; i < left.Length; i++)
            {
                left[i] = NextF();
                int constant = leftBase + i * plan.InnerReduction * sizeof(float) + r * sizeof(float);
                string local = NextR(), local64 = NextRd(), address = NextRd();
                L($"mad.lo.u32 {local}, %r7, {I(plan.ThreadTileM * plan.InnerReduction * sizeof(float))}, {I(constant)};");
                L($"cvt.u64.u32 {local64}, {local};");
                L($"add.u64 {address}, %rd3, {local64};");
                L($"ld.shared.f32 {left[i]}, [{address}];");
            }
            for (int j = 0; j < right.Length; j++)
            {
                right[j] = NextF();
                int constant = rightBase + j * plan.InnerReduction * sizeof(float) + r * sizeof(float);
                string local = NextR(), local64 = NextRd(), address = NextRd();
                L($"mad.lo.u32 {local}, %r6, {I(plan.ThreadTileN * plan.InnerReduction * sizeof(float))}, {I(constant)};");
                L($"cvt.u64.u32 {local64}, {local};");
                L($"add.u64 {address}, %rd3, {local64};");
                L($"ld.shared.f32 {right[j]}, [{address}];");
            }
            for (int i = 0; i < left.Length; i++)
                for (int j = 0; j < right.Length; j++)
                    L($"fma.rn.f32 {accumulators[i, j]}, {left[i]}, {right[j]}, {accumulators[i, j]};");
        }
    }

    private void EmitStores(CodegenTiledOuterProductPlan plan, string[,] accumulators)
    {
        for (int i = 0; i < plan.ThreadTileM; i++)
            for (int j = 0; j < plan.ThreadTileN; j++)
            {
                string localM = NextR(), localN = NextR(), globalM = NextR(), globalN = NextR();
                string element = NextR(), bytes = NextRd(), address = NextRd();
                L($"mad.lo.u32 {localM}, %r7, {I(plan.ThreadTileM)}, {I(i)};");
                L($"mad.lo.u32 {localN}, %r6, {I(plan.ThreadTileN)}, {I(j)};");
                L($"add.u32 {globalM}, %r8, {localM};");
                L($"add.u32 {globalN}, %r9, {localN};");
                L($"mad.lo.u32 {element}, {globalM}, {I(plan.N)}, {globalN};");
                L($"mad.lo.u32 {element}, {element}, {I(plan.Batch)}, %r5;");
                L($"mul.wide.u32 {bytes}, {element}, 4;");
                L($"add.u64 {address}, %rd2, {bytes};");
                L($"st.global.f32 [{address}], {accumulators[i, j]};");
            }
    }

    private string NextR() => "%r" + I(_r++);
    private string NextRd() => "%rd" + I(_rd++);
    private string NextP() => "%p" + I(_p++);
    private string NextF() => "%f" + I(_f++);
    private void L(string line) => _body.Append("    ").Append(line).Append('\n');
    private static string I(int value) => value.ToString(CultureInfo.InvariantCulture);
}
