#if NET5_0_OR_GREATER
using System;
using System.Collections.Generic;

namespace AiDotNet.Tensors.Engines.DirectGpu.CUDA.Ptx;

internal enum DirectPtxRngCoverageStatus
{
    BaselineOnly,
    ExperimentalDirectPtx,
    PlannedDirectPtx,
    ExplicitlyExcluded
}

internal sealed record DirectPtxRngCoverageCell(
    string Api,
    string ExistingImplementation,
    string Semantics,
    string PhysicalLayout,
    string DTypes,
    DirectPtxRngCoverageStatus Status,
    string DirectPtxAssignment);

/// <summary>
/// Executable issue-#849 inventory. Every stochastic family has an explicit
/// assignment; an entry is not evidence that the corresponding PTX has been
/// promoted.
/// </summary>
internal static class DirectPtxRngCoverageManifest
{
    internal static IReadOnlyList<DirectPtxRngCoverageCell> All { get; } =
    [
        new("CudaBackend.Dropout",
            "NVRTC dropout_mask + dropout_forward",
            "inverted dropout; seeded mask is returned for backward",
            "three dense contiguous vectors",
            "FP32",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "v1 fused Philox4x32-10 FP32 forward at exact N=4096/65536/1048576 on SM86"),
        new("CudaBackend.DropoutBackward",
            "NVRTC dropout_backward",
            "gradInput=gradOutput*saved inverted mask",
            "three dense contiguous vectors",
            "FP32",
            DirectPtxRngCoverageStatus.PlannedDirectPtx,
            "fuse with downstream gradient consumer where legal; standalone exact-shape PTX otherwise"),
        new("CudaBackend.DropoutMask / StatelessDropoutMask",
            "NVRTC PCG integer mask generators",
            "stateful and explicit-seed/counter mask generation",
            "dense contiguous vector",
            "FP32",
            DirectPtxRngCoverageStatus.PlannedDirectPtx,
            "Philox4x32-10 v1 standalone masks; materialize only when public API or backward requires"),
        new("CudaBackend.TryFusedBiasDropout",
            "NVRTC bias_dropout",
            "bias add followed by training dropout",
            "row-major [rows,cols] plus vector bias",
            "FP32",
            DirectPtxRngCoverageStatus.PlannedDirectPtx,
            "direct PTX bias+Philox dropout forward/backward pairs keyed by exact rows and cols"),
        new("CudaBackend.GaussianNoise",
            "NVRTC hash plus Box-Muller",
            "normal(mean,stddev) generation",
            "dense contiguous vector",
            "FP32",
            DirectPtxRngCoverageStatus.PlannedDirectPtx,
            "Philox word-pair Box-Muller and fused add-noise consumers"),
        new("CudaBackend.GenerateRandomUniform / DirectGpuTensorEngine.RandomUniformGpu",
            "NVRTC stateless integer generator",
            "explicit-seed uniform values in [min,max)",
            "dense contiguous output vector",
            "FP32 CUDA; generic engine wrapper",
            DirectPtxRngCoverageStatus.PlannedDirectPtx,
            "exact-shape Philox uniform-range PTX with seed/subsequence/counter reservation"),
        new("CudaBackend.GenerateRandomNormal / DirectGpuTensorEngine.RandomNormalGpu",
            "NVRTC stateless integer generator plus Box-Muller",
            "explicit-seed normal(mean,stddev)",
            "dense contiguous output vector",
            "FP32 CUDA; generic engine wrapper",
            DirectPtxRngCoverageStatus.PlannedDirectPtx,
            "exact-shape paired-word Philox normal PTX with odd-length consumption contract"),
        new("CudaBackend.GenerateSecureRandomUniform",
            "host cryptographic bytes uploaded to CUDA",
            "cryptographically secure uniform values in [min,max)",
            "dense contiguous output vector",
            "FP32",
            DirectPtxRngCoverageStatus.ExplicitlyExcluded,
            "fail closed: direct Philox PTX cannot preserve cryptographic unpredictability"),
        new("CudaBackend.GumbelSoftmax / IEngine.GumbelSoftmax",
            "NVRTC RNG plus row softmax; resident composed fallback",
            "Gumbel perturbation, temperature softmax, optional STE path",
            "row-major outer-by-inner",
            "FP32 public CUDA path",
            DirectPtxRngCoverageStatus.PlannedDirectPtx,
            "row-specialized Philox Gumbel generation fused with online softmax and backward"),
        new("CudaBackend importance_sampling / NeRFOperations.ImportanceSampling",
            "NVRTC hash, CDF search, interpolation",
            "one deterministic draw per fine sample and ray",
            "row-major weights/CDF/samples",
            "FP32",
            DirectPtxRngCoverageStatus.PlannedDirectPtx,
            "exact ray/coarse/fine Philox specialization with fused CDF traversal"),
        new("fused_ddim_step diffusion sampler",
            "NVRTC fused DDIM update",
            "scheduler update with stochastic noise when eta is nonzero",
            "dense latent vectors plus scheduler scalars",
            "FP32",
            DirectPtxRngCoverageStatus.PlannedDirectPtx,
            "exact latent-shape Philox noise generation fused into the scheduler update"),
        new("IDeviceRng.Uniform / CpuPhiloxGenerator.Uniform",
            "device-provider or CPU Philox fallback",
            "counter-based uniform range generation",
            "dense tensor storage",
            "FP32/FP64",
            DirectPtxRngCoverageStatus.PlannedDirectPtx,
            "standalone versioned Philox uniform kernels; preserve provider offset contract"),
        new("IDeviceRng.Normal / CpuPhiloxGenerator.Normal",
            "device-provider or CPU Philox fallback",
            "counter-based normal generation with paired-word consumption",
            "dense tensor storage",
            "FP32/FP64",
            DirectPtxRngCoverageStatus.PlannedDirectPtx,
            "standalone Philox normal kernels with documented odd-length counter consumption"),
        new("IDeviceRng.Bernoulli / distribution Bernoulli sampling",
            "CPU/provider sampling",
            "independent probability threshold draws",
            "dense probabilities and/or output",
            "FP32",
            DirectPtxRngCoverageStatus.PlannedDirectPtx,
            "standalone and fused per-element Philox threshold specializations"),
        new("Categorical / Multinomial / Relaxed categorical distributions",
            "CPU Random sampling and tensor compositions",
            "categorical, multinomial, relaxed, and straight-through variants",
            "batch-by-class probabilities/logits",
            "FP32 host API",
            DirectPtxRngCoverageStatus.PlannedDirectPtx,
            "resident prefix/alias or Gumbel-max PTX after device-resident public API exists"),
        new("Tensor random initialization and CreateRandom",
            "host Random fill and backend upload",
            "seeded/unseeded initialization",
            "canonical dense tensor storage",
            "generic public dtype",
            DirectPtxRngCoverageStatus.PlannedDirectPtx,
            "device-resident Philox fill for declared floating/integer dtype and range pairs"),
        new("CpuEngine.TensorRandomUniform / TensorRandomUniformRange / Into variants",
            "host Random/StatelessRandom tensor generation",
            "unseeded or explicit-seed uniform tensor construction and in-place fill",
            "logical dense tensor shape",
            "generic public dtype",
            DirectPtxRngCoverageStatus.PlannedDirectPtx,
            "route resident CUDA tensors to exact-shape Philox fill without host round-trip"),
        new("CpuEngine.TensorRandomNormal / TensorRandomNormalInto",
            "host normal generator",
            "normal(mean,stddev) tensor construction and in-place fill",
            "logical dense tensor shape",
            "generic public dtype",
            DirectPtxRngCoverageStatus.PlannedDirectPtx,
            "route resident CUDA tensors to dtype-specific Philox normal fill"),
        new("CpuEngine.TensorDropoutMask",
            "host StatelessRandom threshold sampling",
            "seeded mask generation with caller-provided scale",
            "logical dense tensor shape",
            "generic public dtype",
            DirectPtxRngCoverageStatus.PlannedDirectPtx,
            "standalone Philox mask PTX only when the API requires materialization"),
        new("Cryptographic and SecureSeededRandom APIs",
            "platform cryptographic RNG / secure host generator",
            "cryptographic unpredictability",
            "host byte stream",
            "bytes and host numeric adapters",
            DirectPtxRngCoverageStatus.ExplicitlyExcluded,
            "fail closed: Philox is deterministic and must never replace a cryptographic contract"),
        new("Normal/LogNormal/HalfNormal/Cauchy/HalfCauchy/Laplace/Uniform/Exponential/Gumbel distributions",
            "CPU Random inverse transforms and Box-Muller sampling",
            "location-scale and reparameterized continuous sampling",
            "host arrays with batch/event broadcasting",
            "FP32",
            DirectPtxRngCoverageStatus.PlannedDirectPtx,
            "algorithm groups require explicit Philox word mapping and fused consumer boundaries"),
        new("Gamma/InverseGamma/Chi2/Beta/StudentT/Pareto/Weibull distributions",
            "CPU Random transformations and rejection samplers",
            "gamma-family, ratio, inverse-transform, and rejection sampling",
            "host arrays with batch/event broadcasting",
            "FP32",
            DirectPtxRngCoverageStatus.BaselineOnly,
            "rejection termination and per-output counter/subsequence reservation must be frozen first"),
        new("Binomial/Geometric/Poisson/NegativeBinomial distributions",
            "CPU Random discrete samplers",
            "count-valued Bernoulli, waiting-time, and rejection/inversion sampling",
            "host arrays with batch/event broadcasting",
            "FP32 encoded samples",
            DirectPtxRngCoverageStatus.BaselineOnly,
            "distribution-specific counter consumption and bounded-loop policy required before PTX"),
        new("MultivariateNormal/DiagonalMultivariateNormal/LowRankMultivariateNormal/Dirichlet distributions",
            "CPU scalar RNG plus dense linear algebra",
            "correlated, diagonal, low-rank, and simplex reparameterized sampling",
            "batch-by-event dense matrices/vectors",
            "FP32",
            DirectPtxRngCoverageStatus.PlannedDirectPtx,
            "fuse Philox normal/gamma generation with exact-shape factor transforms"),
        new("FisherSnedecor/Kumaraswamy/VonMises/ContinuousBernoulli distributions",
            "CPU transform or rejection sampling",
            "specialized continuous distributions",
            "host arrays with batch/event broadcasting",
            "FP32",
            DirectPtxRngCoverageStatus.BaselineOnly,
            "each needs an oracle, bounded termination policy, and counter reservation contract"),
        new("Independent/Transformed/MixtureSameFamily/Expanding distributions",
            "CPU composition around nested DistributionBase.Sample/RSample",
            "shape reinterpretation, transforms, mixture selection, and expansion",
            "composed batch/event layouts",
            "FP32",
            DirectPtxRngCoverageStatus.PlannedDirectPtx,
            "consume promoted primitive samplers; fusion is transform- and layout-specific")
    ];

    internal static DirectPtxRngCoverageCell Get(string api)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(api);
        foreach (DirectPtxRngCoverageCell cell in All)
            if (string.Equals(cell.Api, api, StringComparison.Ordinal)) return cell;
        throw new KeyNotFoundException(
            $"Stochastic API '{api}' is not assigned in the #849 coverage manifest.");
    }
}
#endif
