using System;
using System.Collections.Generic;

namespace AiDotNet.Tensors.Engines.DirectGpu.CUDA.Ptx;

internal enum DirectPtxRngCoverageStatus
{
    ExperimentalDirectPtx,
    ExplicitlyExcluded
}

internal sealed record DirectPtxRngCoverageCell(
    string Api,
    string ExistingImplementation,
    string Semantics,
    string PhysicalLayout,
    string DTypes,
    DirectPtxRngCoverageStatus Status,
    string DirectPtxAssignment);

/// <summary>
/// Executable issue-#849 inventory. Every stochastic family has an explicit
/// assignment; an entry is not evidence that the corresponding PTX has been
/// promoted.
/// </summary>
internal static class DirectPtxRngCoverageManifest
{
    internal static IReadOnlyList<DirectPtxRngCoverageCell> All { get; } =
    [
        new("CudaBackend.Dropout",
            "NVRTC dropout_mask + dropout_forward",
            "inverted dropout; seeded mask is returned for backward",
            "three dense contiguous vectors",
            "FP32",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "v1 fused Philox4x32-10 FP32 forward at exact N=4096/65536/1048576 on SM86"),
        new("IEngine.Dropout",
            "DirectGpuTensorEngine -> IDirectGpuBackend.Dropout",
            "training returns inverted-dropout output plus backward-visible mask; inference is identity",
            "canonical dense tensor",
            "generic API; FP32 direct CUDA",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "admitted training FP32 tensors route to PtxFusedPhiloxDropoutF32Kernel; all other contracts retain the established implementation"),
        new("DirectGpuTensorEngine.DropoutGpu",
            "IDirectGpuBackend.Dropout",
            "explicit resident dropout forward returning output and saved mask",
            "three canonical dense tensors",
            "FP32 direct CUDA",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "admitted training tensors route through CudaBackend.Dropout to PtxFusedPhiloxDropoutF32Kernel"),
        new("CudaBackend.DropoutBackward",
            "NVRTC dropout_backward",
            "gradInput=gradOutput*saved inverted mask",
            "three dense contiguous vectors",
            "FP32",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "v1 standalone exact-shape saved-mask float4 PTX on SM86; downstream gradient fusion remains legal when a consumer owns the boundary"),
        new("IEngine.DropoutBackward",
            "DirectGpuTensorEngine -> IDirectGpuBackend.DropoutBackward",
            "gradInput=gradOutput*saved inverted mask",
            "canonical dense tensors",
            "generic API; FP32 direct CUDA",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "admitted FP32 tensors route to PtxDropoutBackwardF32Kernel"),
        new("DirectGpuTensorEngine.DropoutBackwardGpu",
            "IDirectGpuBackend.DropoutBackward",
            "explicit resident dropout backward",
            "three dense contiguous vectors",
            "FP32",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "admitted exact shapes route to PtxDropoutBackwardF32Kernel"),
        new("CudaBackend.DropoutMask",
            "NVRTC dropout_mask",
            "explicit-seed inverted Bernoulli keep mask",
            "dense contiguous vector",
            "FP32",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "v1 exact-shape Philox4x32-10 keep-threshold mask on SM86"),
        new("CudaBackend.GenerateStatelessDropoutMask",
            "NVRTC PCG integer mask generators",
            "explicit-seed drop-threshold mask with caller-provided scale",
            "dense contiguous vector",
            "FP32",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "v1 exact-shape Philox4x32-10 drop-threshold mask on SM86"),
        new("IEngine.TensorDropoutMask",
            "DirectGpuTensorEngine -> GenerateStatelessDropoutMask",
            "seeded or engine-stream-owned drop-threshold mask with public scale",
            "canonical dense tensor",
            "generic API; FP32 direct CUDA",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "both seeded and unseeded admitted FP32 calls use PtxPhiloxFillF32Kernel directly with no random/threshold temporary"),
        new("DirectGpuTensorEngine.FusedBiasDropout",
            "NVRTC bias_dropout",
            "bias add followed by training dropout",
            "row-major [rows,cols] plus vector bias",
            "FP32",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "v1 exact [16|256|4096,256] bias+Philox inverted-dropout PTX; output and backward-required public mask are the only writes and no private temporary is allocated"),
        new("IEngine.GenerateDropoutMask",
            "temporary CUDA output followed by synchronous Vector download",
            "host Vector inverted-dropout mask with public scale",
            "host-owned dense vector; temporary resident generation boundary",
            "generic API; FP32 direct CUDA generation",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "exact FP32 lengths generate through PtxPhiloxFillF32Kernel before the unavoidable public host-result transfer; resident callers must use TensorDropoutMask"),
        new("CudaBackend.GaussianNoise",
            "NVRTC hash plus Box-Muller",
            "normal(mean,stddev) generation",
            "dense contiguous vector",
            "FP32",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "v1 exact-shape paired-word Philox Box-Muller fill on SM86; fused add-noise consumers remain separate scope"),
        new("IEngine.GenerateGaussianNoise",
            "temporary CUDA output followed by synchronous Vector download",
            "host Vector normal(mean,stddev) generation",
            "host-owned dense vector; temporary resident generation boundary",
            "generic API; FP32 direct CUDA generation",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "exact FP32 lengths generate through PtxPhiloxFillF32Kernel before the unavoidable public host-result transfer; resident callers use RandomNormalGpu/TensorRandomNormal"),
        new("CudaBackend.GenerateRandomUniform",
            "NVRTC stateless integer generator",
            "explicit-seed uniform values in [min,max)",
            "dense contiguous output vector",
            "FP32",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "v1 exact-shape Philox uniform-range PTX with explicit seed/subsequence/counter ABI on SM86"),
        new("DirectGpuTensorEngine.RandomUniformGpu",
            "IDirectGpuBackend.GenerateRandomUniform",
            "explicit-seed resident uniform initialization",
            "canonical dense tensor",
            "FP32",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "admitted exact shapes route to PtxPhiloxFillF32Kernel.Uniform"),
        new("CudaBackend.GenerateRandomNormal",
            "NVRTC stateless integer generator plus Box-Muller",
            "explicit-seed normal(mean,stddev)",
            "dense contiguous output vector",
            "FP32",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "v1 exact-shape paired-word Philox normal PTX; admitted buckets are divisible by four so no odd-length contract is needed"),
        new("DirectGpuTensorEngine.RandomNormalGpu",
            "IDirectGpuBackend.GenerateRandomNormal",
            "explicit-seed resident normal initialization",
            "canonical dense tensor",
            "FP32",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "admitted exact shapes route to PtxPhiloxFillF32Kernel.Normal"),
        new("CudaBackend.GenerateSecureRandomUniform",
            "host cryptographic bytes uploaded to CUDA",
            "cryptographically secure uniform values in [min,max)",
            "dense contiguous output vector",
            "FP32",
            DirectPtxRngCoverageStatus.ExplicitlyExcluded,
            "fail closed: direct Philox PTX cannot preserve cryptographic unpredictability"),
        new("CudaBackend.GumbelSoftmax",
            "NVRTC RNG plus row softmax; resident composed fallback",
            "Gumbel perturbation and temperature softmax",
            "row-major outer-by-inner",
            "FP32",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "v1 one-warp-per-row Philox Gumbel generation fused with register-resident softmax for exact [128|2048|32768,32] FP32 layouts on SM86"),
        new("IEngine.GumbelSoftmax",
            "DirectGpuTensorEngine -> IGpuBatchExecution.GumbelSoftmax",
            "soft sample or hard straight-through projection",
            "canonical row-major last-axis classes",
            "generic API; FP32 direct CUDA",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "admitted soft stage routes to PtxFusedGumbelSoftmax32F32Kernel; hard projection reuses that resident soft result"),
        new("IEngine.GumbelSoftmaxBackward",
            "resident SoftmaxBackward plus scalar scale",
            "softmax Jacobian-vector product divided by temperature",
            "canonical row-major last-axis classes",
            "generic API; FP32 direct CUDA",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "v1 exact [128|2048|32768,32] one-warp PtxGumbelSoftmaxBackward32F32Kernel"),
        new("CudaBackend.ImportanceSampling",
            "NVRTC hash, CDF search, interpolation",
            "one deterministic draw per fine sample and ray",
            "row-major weights/CDF/samples",
            "FP32",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "v1 exact [64|1024|16384 rays,64 coarse,64 fine] one-warp Philox specialization; coarse t/weights stage once to shared memory and CDF traversal is fully unrolled/predicated"),
        new("IEngine.ImportanceSampling",
            "DirectGpuTensorEngine -> IImportanceSamplingBackend",
            "NeRF hierarchical sampling",
            "canonical row-major rays by samples",
            "generic API; FP32 direct CUDA",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "admitted 64/64 FP32 contracts route to PtxFusedImportanceSampling64F32Kernel"),
        new("IFusedAdvancedKernels.FusedDDIMStep",
            "NVRTC fused DDIM update",
            "currently advertised deterministic scheduler update; public API has no eta/noise argument",
            "dense latent vectors plus scheduler scalars",
            "FP32",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "v1 exact-shape float4 DDIM update on SM86 with FP64 host coefficient collapse; stochastic eta/noise is explicitly not claimed because the API does not expose it"),
        new("CudaBackend.RRelu",
            "NVRTC rrelu saved-noise consumer",
            "output=x>=0 ? x : savedNoise*x",
            "three dense contiguous vectors",
            "FP32",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "v1 exact-shape float4 PtxRreluF32Kernel forward on SM86"),
        new("CudaBackend.RReluBackward",
            "NVRTC rrelu_backward",
            "gradInput=gradOutput*(input>=0 ? 1 : savedNoise)",
            "four dense contiguous vectors",
            "FP32",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "v1 exact-shape float4 PtxRreluF32Kernel backward on SM86"),
        new("IEngine.TensorRReLU",
            "GenerateRandomUniform plus NVRTC rrelu; inference uses midpoint slopes",
            "training random leaky-ReLU with backward-visible saved slopes",
            "canonical dense tensor plus saved-noise/output tensors",
            "generic API; FP32 direct CUDA",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "admitted contiguous training calls route to one PtxFusedPhiloxRreluF32Kernel launch; evaluation and unsupported contracts retain the established path"),
        new("CuRand.Uniform",
            "device-provider or CPU Philox fallback",
            "host Tensor output with counter-based uniform generation",
            "host-owned dense tensor storage",
            "FP32/FP64",
            DirectPtxRngCoverageStatus.ExplicitlyExcluded,
            "fail closed: this host-output API would require temporary VRAM, synchronization, and a device-to-host copy; resident IDirectGpuBackend generation owns the PTX route"),
        new("CuRand.Normal",
            "device-provider or CPU Philox fallback",
            "host Tensor output with counter-based normal generation",
            "host-owned dense tensor storage",
            "FP32/FP64",
            DirectPtxRngCoverageStatus.ExplicitlyExcluded,
            "fail closed: a PTX bridge cannot meet the no-temporary resident gate for this host-output contract"),
        new("CuRand.Bernoulli",
            "CPU/provider sampling",
            "host Tensor output with independent probability threshold draws",
            "host-owned dense tensor storage",
            "FP32",
            DirectPtxRngCoverageStatus.ExplicitlyExcluded,
            "fail closed: resident Bernoulli/dropout-mask generation is direct PTX, while this host-output API retains its allocation-free CPU Philox path"),
        new("IEngine.TensorCategoricalSample",
            "CPU categorical oracle plus explicitly seeded resident GPU Gumbel-max fallback",
            "one categorical draw per slice, returned as one-hot output",
            "batch-by-class probabilities/logits",
            "generic CPU; exact FP32 CUDA",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "v1 exact [128|2048|32768,32] one-warp Philox CDF scan and one-hot output on SM86; no global CDF/index intermediate"),
        new("Tensor.CreateRandom",
            "AiDotNetEngine.Current.TensorRandomUniform",
            "engine-selected unseeded initialization",
            "canonical dense tensor storage",
            "generic public dtype",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "FP32 resident initialization routes through the exact-shape Philox uniform fill; other dtypes and shapes fail closed"),
        new("IEngine.TensorRandomUniform",
            "host Random/StatelessRandom tensor generation",
            "unseeded uniform tensor construction",
            "logical dense tensor shape",
            "generic public dtype",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "DirectGpuTensorEngine routes admitted resident FP32 construction to exact-shape Philox without a host round-trip"),
        new("IEngine.TensorRandomUniformRange",
            "host Random/StatelessRandom tensor generation",
            "seeded or engine-stream-owned uniform range construction",
            "logical dense tensor shape",
            "generic public dtype",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "DirectGpuTensorEngine routes admitted FP32 construction to PtxPhiloxFillF32Kernel.Uniform"),
        new("IEngine.TensorRandomUniformRangeInto",
            "host Random/StatelessRandom in-place fill",
            "seeded or engine-stream-owned uniform range fill",
            "logical dense tensor shape",
            "generic public dtype",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "DirectGpuTensorEngine routes admitted FP32 fills through PtxPhiloxFillF32Kernel.Uniform before the existing destination transfer boundary"),
        new("IEngine.TensorRandomNormal",
            "host normal generator",
            "normal(mean,stddev) tensor construction",
            "logical dense tensor shape",
            "generic public dtype",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "DirectGpuTensorEngine routes admitted resident FP32 construction to the exact-shape paired-word normal specialization"),
        new("IEngine.TensorRandomNormalInto",
            "host normal in-place fill",
            "normal(mean,stddev) tensor fill",
            "logical dense tensor shape",
            "generic public dtype",
            DirectPtxRngCoverageStatus.ExperimentalDirectPtx,
            "DirectGpuTensorEngine routes admitted FP32 fills through PtxPhiloxFillF32Kernel.Normal before the existing destination transfer boundary"),
        new("Cryptographic and SecureSeededRandom APIs",
            "platform cryptographic RNG / secure host generator",
            "cryptographic unpredictability",
            "host byte stream",
            "bytes and host numeric adapters",
            DirectPtxRngCoverageStatus.ExplicitlyExcluded,
            "fail closed: Philox is deterministic and must never replace a cryptographic contract")
    ];

    internal static DirectPtxRngCoverageCell Get(string api)
    {
        PtxCompat.ThrowIfNullOrWhiteSpace(api, nameof(api));
        foreach (DirectPtxRngCoverageCell cell in All)
            if (string.Equals(cell.Api, api, StringComparison.Ordinal)) return cell;
        throw new KeyNotFoundException(
            $"Stochastic API '{api}' is not assigned in the #849 coverage manifest.");
    }
}
