using System;
using System.Collections.Generic;

namespace AiDotNet.Tensors.Engines.DirectGpu.CUDA.Ptx;

internal enum DirectPtxConvolutionCoverageStatus
{
    BaselineOnly,
    ExperimentalDirectPtx,
    PlannedDirectPtx
}

internal sealed record DirectPtxConvolutionCoverageCell(
    string Api,
    string ExistingImplementation,
    string Semantics,
    string PhysicalLayout,
    string DTypes,
    DirectPtxConvolutionCoverageStatus Status,
    string DirectPtxAssignment);

/// <summary>
/// Executable issue-#841 inventory. Entries remain explicit even when several
/// public overloads share one backend primitive, preventing a future PR from
/// silently declaring the entire family ported after one specialization.
/// </summary>
internal static class DirectPtxConvolutionCoverageManifest
{
    private static DirectPtxConvolutionCoverageCell Planned(
        string api, string implementation, string semantics, string layout,
        string dtypes, string assignment) =>
        new(api, implementation, semantics, layout, dtypes,
            DirectPtxConvolutionCoverageStatus.PlannedDirectPtx, assignment);

    internal static IReadOnlyList<DirectPtxConvolutionCoverageCell> All { get; } =
    [
        new("DirectGpuTensorEngine.FusedConv2D",
            "cuDNN or CUDA Conv2D + NVRTC bias + activation",
            "inference convolution with optional bias and activation",
            "NCHW input/output, OIHW weights", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/C64/H16/W16/K64 1x1 FP32 bias+ReLU; all other contracts fall back"),
        new("CudaBackend.TryDirectPtxFusedConv2DBiasRelu",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 fused inference contract", "exact contiguous NCHW/OIHW", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only 1x1 specialization, disabled by default"),
        new("CudaBackend.TryDirectPtxFusedConv2D3x3BiasRelu",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "general 3x3 fused bias+ReLU inference contract", "exact contiguous NCHW/OIHW", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only 3x3 channel-loop + fused epilogue specialization, disabled by default"),
        new("IEngine.Conv1D",
            "CUDA Conv1D routed through Conv2D with established fallback owned by caller",
            "1D forward", "NCL input/output as H1-NCHW, OIL weights as H1-OIHW", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/Cin64/L256/Cout64 r3 s1 p1 FP32 halo-predicated; all other contracts fall back"),
        new("CudaBackend.TryDirectPtxConv1D",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 Conv1D contract", "exact contiguous NCL/OIL (H1)", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only specialization, disabled by default"),
        new("IEngine.Conv1DBackwardInput",
            "CUDA direct backward-input kernel with established fallback owned by caller",
            "1D input gradient", "NCL grad-out/in as H1-NCHW, OIL weights", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/Cin64/L256/Cout64 r3 s1 p1 FP32 (transpose of forward); all else falls back"),
        new("CudaBackend.TryDirectPtxConv1DBackwardInput",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 Conv1D backward-input contract", "exact contiguous NCL/OIL (H1)", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only transposed specialization, disabled by default"),
        new("IEngine.Conv1DBackwardKernel",
            "CUDA direct backward-weight kernel with established fallback owned by caller",
            "1D weight gradient", "NCL grad-out/input as H1-NCHW, OIL grad-weight", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/Cin64/L256/Cout64 r3 s1 p1 FP32 thread-per-weight full-dot (deterministic); all else falls back"),
        new("CudaBackend.TryDirectPtxConv1DBackwardWeight",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 Conv1D backward-weight contract", "exact contiguous NCL/OIL (H1)", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only thread-private-dot specialization, disabled by default"),
        new("IEngine.Conv2D",
            "cuDNN, Winograd, tiled NVRTC, or direct NVRTC with established fallback owned by caller",
            "2D forward", "NCHW/OIHW plus public format overload", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/Cin64/H16/W16/Cout64 3x3 s1 p1 FP32 halo-predicated channel loop; 1x1 + tiled + Tensor-Core families still fall back"),
        new("CudaBackend.TryDirectPtxConv2D3x3",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 general 3x3 forward contract", "exact contiguous NCHW/OIHW", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only specialization, disabled by default"),
        new("IEngine.Conv2DBackwardInput",
            "cuDNN or CUDA direct backward-input with established fallback owned by caller",
            "2D input gradient", "NCHW grad-out/in, OIHW weights", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 1x1 (transposed mat-vec) and general 3x3 s1 p1 exact N1/C64/H16/W16/K64 FP32 specializations; all else falls back"),
        new("CudaBackend.TryDirectPtxConv2DBackwardInput",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 1x1 backward-input contract", "exact contiguous NCHW/OIHW", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only transposed specialization, disabled by default"),
        new("CudaBackend.TryDirectPtxConv2D3x3BackwardInput",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "general 3x3 backward-input contract", "exact contiguous NCHW/OIHW", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only transposed channel-loop specialization, disabled by default"),
        new("IEngine.Conv2DBackwardKernel",
            "cuDNN or CUDA direct backward-weight with established fallback owned by caller",
            "2D weight gradient", "NCHW grad-out/input, OIHW grad-weight", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 1x1 and general 3x3 s1 p1 exact N1/C64/H16/W16/K64 FP32 thread-per-weight full-dot (deterministic); all else falls back"),
        new("CudaBackend.TryDirectPtxConv2DBackwardWeight",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 1x1 backward-weight contract", "exact contiguous NCHW/OIHW", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only thread-private-dot specialization, disabled by default"),
        new("CudaBackend.TryDirectPtxConv2D3x3BackwardWeight",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "general 3x3 backward-weight contract", "exact contiguous NCHW/OIHW", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only thread-private full-HxW-dot specialization, disabled by default"),
        new("DirectGpuTensorEngine.Conv2DBackwardBiasGpu",
            "CUDA reduction with established fallback owned by caller",
            "2D bias gradient", "NCHW grad-output to per-channel vector", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/K64/H16/W16 FP32 warp-per-channel deterministic reduction; all else falls back"),
        new("CudaBackend.TryDirectPtxConv2DBackwardBias",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 bias-gradient contract", "exact contiguous NCHW to vector", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only warp-reduction specialization, disabled by default"),
        new("IEngine.Conv3D",
            "CUDA direct 3D kernel with established fallback owned by caller",
            "3D forward", "NCDHW input/output, OIDHW weights", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/Cin16/D8/H8/W8/Cout16 3x3x3 s1 p1 FP32 27-tap halo-predicated channel loop; all else falls back"),
        new("CudaBackend.TryDirectPtxConv3D3x3x3",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 3x3x3 forward contract", "exact contiguous NCDHW/OIDHW (byte-extent validated)", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only 3D specialization, disabled by default"),
        new("IEngine.Conv3DBackwardInput",
            "CPU fallback/current backend composition with established fallback owned by caller",
            "3D input gradient", "NCDHW grad-out/in, OIDHW weights", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/Cin16/D8/H8/W8/Cout16 3x3x3 s1 p1 FP32 27-tap transpose; all else falls back"),
        new("CudaBackend.TryDirectPtxConv3D3x3x3BackwardInput",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 3x3x3 backward-input contract", "exact contiguous NCDHW/OIDHW (byte-extent validated)", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only 3D transpose specialization, disabled by default"),
        new("IEngine.Conv3DBackwardKernel",
            "CPU fallback/current backend composition with established fallback owned by caller",
            "3D weight gradient", "NCDHW grad-out/input, OIDHW grad-weight", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/Cin16/D8/H8/W8/Cout16 3x3x3 s1 p1 FP32 thread-per-weight full-volume dot (deterministic); all else falls back"),
        new("CudaBackend.TryDirectPtxConv3D3x3x3BackwardWeight",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 3x3x3 backward-weight contract", "exact contiguous NCDHW/OIDHW (byte-extent validated)", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only thread-private full-volume-dot specialization, disabled by default"),
        new("IEngine.DepthwiseConv1D",
            "reshape to CUDA depthwise Conv2D with established fallback owned by caller",
            "depthwise 1D forward", "NCL input/output as H1-NCHW, per-channel OIL weights", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/C64/L256 r3 s1 p1 FP32 native per-channel 1D (no channel loop); all else falls back"),
        new("CudaBackend.TryDirectPtxDepthwiseConv1D",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 DepthwiseConv1D contract", "exact contiguous NCL/OIL (H1)", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only per-channel specialization, disabled by default"),
        new("IEngine.DepthwiseConv1DBackwardInput",
            "CPU/current backend path with established fallback owned by caller",
            "depthwise 1D input gradient", "NCL grad-out/in as H1-NCHW, per-channel OIL weights", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/C64/L256 r3 s1 p1 FP32 per-channel transpose (no channel loop); all else falls back"),
        new("CudaBackend.TryDirectPtxDepthwiseConv1DBackwardInput",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 DepthwiseConv1D backward-input contract", "exact contiguous NCL/OIL (H1)", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only per-channel transposed specialization, disabled by default"),
        new("IEngine.DepthwiseConv1DBackwardKernel",
            "CPU/current backend path with established fallback owned by caller",
            "depthwise 1D weight gradient", "NCL grad-out/input as H1-NCHW, per-channel OIL grad-weight", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/C64/L256 r3 s1 p1 FP32 thread-per-weight full-L dot (deterministic); all else falls back"),
        new("CudaBackend.TryDirectPtxDepthwiseConv1DBackwardWeight",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 DepthwiseConv1D backward-weight contract", "exact contiguous NCL/OIL (H1)", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only per-channel thread-private-dot specialization, disabled by default"),
        new("IEngine.DepthwiseConv2D",
            "CUDA NVRTC depthwise kernel with established fallback owned by caller",
            "depthwise 2D forward", "NCHW input/output, depthwise OIHW weights",
            "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/C64/H16/W16 3x3 stride1 pad1 FP32; all other contracts fall back"),
        new("CudaBackend.TryDirectPtxDepthwiseConv2D3x3",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 depthwise contract", "exact contiguous NCHW/depthwise OIHW", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only specialization, disabled by default"),
        new("IEngine.DepthwiseConv2DBackwardInput",
            "CUDA depthwise backward-input with established fallback owned by caller",
            "depthwise 2D input gradient", "NCHW grad-out/in, depthwise OIHW weights",
            "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/C64/H16/W16 3x3 stride1 pad1 FP32 (transpose of forward); all else falls back"),
        new("CudaBackend.TryDirectPtxDepthwiseConv2D3x3BackwardInput",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 depthwise backward-input contract", "exact contiguous NCHW/depthwise OIHW", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only specialization, disabled by default"),
        new("IEngine.DepthwiseConv2DBackwardKernel",
            "CUDA depthwise backward-weight with established fallback owned by caller",
            "depthwise 2D weight gradient", "NCHW grad-out/input, depthwise OIHW grad-weight",
            "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/C64/H16/W16 3x3 stride1 pad1 FP32, warp-per-channel deterministic reduction; all else falls back"),
        new("CudaBackend.TryDirectPtxDepthwiseConv2D3x3BackwardWeight",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 depthwise backward-weight contract", "exact contiguous NCHW/depthwise OIHW", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only warp-reduction specialization, disabled by default"),
        new("IEngine.ConvTranspose2D",
            "CUDA NVRTC transposed convolution with established fallback owned by caller",
            "2D transposed forward", "NCHW input/output, IOHW weights", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/Cin64/H16/W16/Cout64 3x3 s1 p1 FP32 halo-predicated channel loop; all else falls back"),
        new("CudaBackend.TryDirectPtxConvTranspose2D3x3",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 3x3 transposed forward contract", "exact contiguous NCHW/IOHW", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only transposed specialization, disabled by default"),
        new("IEngine.ConvTranspose2DBackwardInput",
            "CUDA direct transposed backward-input with established fallback owned by caller",
            "transposed input gradient", "NCHW grad in/out, IOHW weights", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/Cin64/H16/W16/Cout64 3x3 s1 p1 FP32 (adjoint = forward-style conv); all else falls back"),
        new("CudaBackend.TryDirectPtxConvTranspose2D3x3BackwardInput",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 3x3 transposed backward-input contract", "exact contiguous NCHW/IOHW", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only adjoint-conv specialization, disabled by default"),
        new("IEngine.ConvTranspose2DBackwardKernel",
            "CUDA direct transposed backward-weight with established fallback owned by caller",
            "transposed weight gradient", "NCHW grad-out/input, IOHW grad-weight", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/Cin64/H16/W16/Cout64 3x3 s1 p1 FP32 thread-per-weight full-dot (deterministic); all else falls back"),
        new("CudaBackend.TryDirectPtxConvTranspose2D3x3BackwardWeight",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 3x3 transposed backward-weight contract", "exact contiguous NCHW/IOHW", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only thread-private full-HxW-dot specialization, disabled by default"),
        new("IEngine.ConvTranspose3D",
            "CUDA direct 3D transposed kernel with established fallback owned by caller",
            "3D transposed forward", "NCDHW input/output, IODHW weights", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/Cin16/D8/H8/W8/Cout16 3x3x3 s1 p1 FP32 27-tap transpose (negated offsets, reversed halo); all else falls back"),
        new("CudaBackend.TryDirectPtxConvTranspose3D3x3x3",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 3x3x3 transposed forward contract", "exact contiguous NCDHW/IODHW (byte-extent validated)", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only 3D transpose specialization, disabled by default"),
        new("IEngine.ConvTranspose3DBackwardInput",
            "CUDA direct 3D transposed backward-input with established fallback owned by caller",
            "3D transposed input gradient", "NCDHW grad-output/grad-input, IODHW weights", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/Cin16/D8/H8/W8/Cout16 3x3x3 s1 p1 FP32 regular-conv gather over co (deterministic); all else falls back"),
        new("CudaBackend.TryDirectPtxConvTranspose3D3x3x3BackwardInput",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 3x3x3 transposed backward-input contract", "exact contiguous NCDHW/IODHW (byte-extent validated)", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only 3D transpose backward-input specialization, disabled by default"),
        Planned("IEngine.ConvTranspose3DBackwardKernel", "CPU/current backend fallback", "3D transposed weight gradient", "NCDHW/IODHW", "generic", "CUDA deterministic backward-weight PTX"),
        new("IEngine.DeformableConv2D",
            "CUDA direct DCNv2 forward with established fallback owned by caller",
            "offset/mask deformable forward (bilinear)", "NCHW input/output, OIHW weights, [2*kHkW,outH,outW] offsets, [kHkW,outH,outW] mask", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/Cin4/H8/W8/Cout4 3x3 s1 p1 dil1 v2 FP32 fused bilinear-sample + modulation + convolution (single group); all else falls back"),
        new("CudaBackend.TryDirectPtxDeformableConv2D",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 deformable forward contract", "exact contiguous NCHW/OIHW plus offsets/mask (byte-extent validated)", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only bilinear-sampling deformable specialization, disabled by default"),
        new("IEngine.DeformableConv2DBackwardInput",
            "CUDA direct DCNv2 backward-input with established fallback owned by caller",
            "input gradient (deterministic bilinear-transpose gather)", "NCHW grad-output/grad-input, OIHW weights, offset/mask planes", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/Cin4/H8/W8/Cout4 3x3 s1 p1 dil1 v2 FP32 thread-per-input g(d)=max(0,1-|d|) transpose gather over tap/pos/co (deterministic, no atomics); all else falls back"),
        new("CudaBackend.TryDirectPtxDeformableConv2DBackwardInput",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 deformable backward-input contract", "exact contiguous NCHW/OIHW plus offsets/mask (byte-extent validated)", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only input-gradient gather specialization, disabled by default"),
        new("IEngine.DeformableConv2DBackwardKernel",
            "CUDA direct DCNv2 backward-weight with established fallback owned by caller",
            "weight gradient (spatial reduction)", "NCHW grad/input, OIHW grad-weight, offsets/mask planes", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/Cin4/H8/W8/Cout4 3x3 s1 p1 dil1 v2 FP32 thread-per-weight spatial reduction recomputing bilinear (deterministic); all else falls back"),
        new("CudaBackend.TryDirectPtxDeformableConv2DBackwardWeights",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 deformable backward-weight contract", "exact contiguous NCHW/OIHW plus offsets/mask (byte-extent validated)", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only bilinear-recompute weight-gradient specialization, disabled by default"),
        new("IEngine.DeformableConv2DBackwardOffset",
            "CUDA direct DCNv2 backward-offset with established fallback owned by caller",
            "offset gradient (bilinear spatial derivative)", "NCHW grad/input, OIHW weights, offset/mask planes, [2*kHkW,outH,outW] grad-offset", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/Cin4/H8/W8/Cout4 3x3 s1 p1 dil1 v2 FP32 thread-per-(tap,pos) dual dOffY/dOffX bilinear-derivative reduction (deterministic); all else falls back"),
        new("CudaBackend.TryDirectPtxDeformableConv2DBackwardOffset",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 deformable backward-offset contract", "exact contiguous NCHW/OIHW plus offsets/mask (byte-extent validated)", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only offset-gradient (spatial-derivative) specialization, disabled by default"),
        new("IEngine.DeformableConv2DBackwardMask",
            "CUDA direct DCNv2 backward-mask with established fallback owned by caller",
            "mask gradient (ci/co reduction)", "NCHW grad/input, OIHW weights, offset planes, [kHkW,outH,outW] grad-mask", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/Cin4/H8/W8/Cout4 3x3 s1 p1 dil1 v2 FP32 thread-per-mask bilinear-once + ci/co reduction (deterministic); all else falls back"),
        new("CudaBackend.TryDirectPtxDeformableConv2DBackwardMask",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 deformable backward-mask contract", "exact contiguous NCHW/OIHW plus offsets (byte-extent validated)", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only mask-gradient specialization, disabled by default"),
        Planned("IEngine.DeformableConv2DGrouped", "CUDA grouped deformable kernel", "grouped/deform-group forward", "NCHW plus grouped offsets/mask", "generic/FP32", "group-specialized PTX"),
        Planned("IEngine.DeformableConv2DGroupedBackward", "CUDA grouped deformable backward family", "all grouped gradients", "NCHW plus grouped offsets/mask", "generic/FP32", "four deterministic grouped backward families"),
        new("IEngine.LocallyConnectedConv2D",
            "CUDA direct locally-connected kernel with established fallback owned by caller",
            "unshared spatial weights forward", "NCHW input/output, per-position [outHW,Cout,Cin,kH,kW] weights", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/Cin8/H8/W8/Cout8 3x3 s1 p1 FP32 per-position weight-base halo-predicated channel loop; all else falls back"),
        new("CudaBackend.TryDirectPtxLocallyConnectedConv2D",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 locally-connected forward contract", "exact contiguous NCHW plus per-position weights (byte-extent validated)", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only per-position specialization, disabled by default"),
        new("IEngine.LocallyConnectedConv2DBackwardInput",
            "CUDA direct locally-connected backward-input with established fallback owned by caller",
            "input gradient (transpose gather)", "NCHW grad, per-position [outHW,Cout,Cin,kH,kW] weights", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/Cin8/H8/W8/Cout8 3x3 s1 p1 FP32 thread-per-input transpose gather over co (deterministic); all else falls back"),
        new("CudaBackend.TryDirectPtxLocallyConnectedConv2DBackwardInput",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 locally-connected backward-input contract", "exact contiguous NCHW plus per-position weights (byte-extent validated)", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only per-position transpose-gather specialization, disabled by default"),
        new("IEngine.LocallyConnectedConv2DBackwardWeights",
            "CUDA direct locally-connected backward-weight with established fallback owned by caller",
            "weight gradient (single product, no reduction)", "NCHW grad/input, per-position [outHW,Cout,Cin,kH,kW] grad-weight", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/Cin8/H8/W8/Cout8 3x3 s1 p1 FP32 thread-per-weight single-product halo-predicated (deterministic); all else falls back"),
        new("CudaBackend.TryDirectPtxLocallyConnectedConv2DBackwardWeights",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 locally-connected backward-weight contract", "exact contiguous NCHW plus per-position grad-weight (byte-extent validated)", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only per-weight single-product specialization, disabled by default"),
        new("IEngine.LocallyConnectedConv2DBackwardBias",
            "CUDA direct batch-reduction with established fallback owned by caller",
            "bias gradient (batch reduction)", "NCHW grad-output to per-position [Cout,outH,outW] bias", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N4/Cout8/outH8/outW8 FP32 thread-per-bias batch reduction (deterministic); all else falls back"),
        new("CudaBackend.TryDirectPtxLocallyConnectedConv2DBackwardBias",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 locally-connected backward-bias contract", "exact contiguous NCHW grad to per-position bias (byte-extent validated)", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only per-bias batch-reduction specialization, disabled by default"),
        new("IEngine.FusedConv3D",
            "CUDA Conv3D plus epilogue with established fallback owned by caller",
            "3D inference epilogue fusion", "NCDHW input/output, OIDHW weights, bias vector", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/Cin16/D8/H8/W8/Cout16 3x3x3 s1 p1 FP32 fused bias+ReLU (no intermediate); all else falls back"),
        new("CudaBackend.TryDirectPtxFusedConv3D3x3x3BiasRelu",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 3x3x3 fused bias+ReLU contract", "exact contiguous NCDHW/OIDHW (byte-extent validated)", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only 3D fused-epilogue specialization, disabled by default"),
        new("IEngine.FusedConvTranspose2D",
            "CUDA transposed convolution plus epilogue with established fallback owned by caller",
            "transposed inference fusion", "NCHW input/output, IOHW weights, bias vector", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/Cin64/H16/W16/Cout64 3x3 s1 p1 FP32 fused bias+ReLU; all else falls back"),
        new("CudaBackend.TryDirectPtxFusedConvTranspose2D3x3BiasRelu",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 3x3 transposed fused bias+ReLU contract", "exact contiguous NCHW/IOHW", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only transposed + fused-epilogue specialization, disabled by default"),
        new("IEngine.Unfold",
            "CUDA im2col/unfold NVRTC kernels with established fallback owned by caller",
            "materialized patch extraction", "NCHW to [C*9, H*W] row-major matrix", "generic public; CUDA FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/C64/H16/W16 3x3 s1 p1 FP32 halo-masked gather (bit-exact); all else falls back"),
        new("CudaBackend.TryDirectPtxUnfold",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 unfold/im2col contract", "exact contiguous NCHW to row-major", "FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only gather specialization, disabled by default"),
        new("CudaBackend.Conv2dDirectFp16Hw",
            "NVRTC half-weight direct convolution with established fallback owned by caller",
            "FP16 input+weights, FP32 accumulation/output", "NCHW/OIHW half input+weights, FP32 output", "mixed FP16/FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "v1 exact N1/C64/H16/W16/K64 1x1 FP16-in/FP32-out cvt.f32.f16 dot; all else falls back"),
        new("CudaBackend.TryDirectPtxConv2DFp16K1",
            "new direct Driver-API PTX route with established fallback owned by caller",
            "same v1 FP16 1x1 mixed-precision contract", "exact contiguous NCHW/OIHW half in, FP32 out", "mixed FP16/FP32",
            DirectPtxConvolutionCoverageStatus.ExperimentalDirectPtx,
            "hand-emitted sm_86 pointer-only FP16-storage specialization, disabled by default"),
        Planned("CudaBackend.Im2colKNFp16", "NVRTC fused im2col+FP16 conversion", "FP16 Tensor-Core GEMM preparation", "NCHW to KxN half", "FP16/FP32", "fuse producer into PTX convolution tiles"),
        Planned("CudaBackend.UnfoldKNFp16FromFp16", "NVRTC FP16 im2col", "FP16 patch extraction", "NCHW-half to KxN-half", "FP16", "fuse producer into PTX convolution tiles")
    ];

    internal static DirectPtxConvolutionCoverageCell Get(string api)
    {
        PtxCompat.ThrowIfNullOrWhiteSpace(api, nameof(api));
        foreach (DirectPtxConvolutionCoverageCell cell in All)
            if (string.Equals(cell.Api, api, StringComparison.Ordinal)) return cell;
        throw new KeyNotFoundException(
            $"Convolution API '{api}' is not assigned in the #841 coverage manifest.");
    }
}
