//! SM86 PTX emitter — Rust half of the bake-off.
//!
//! Structurally identical to `PtxAffineEmitter.cs`: same unroll policy, same
//! decomposition order, same derived guards, so any difference in the measured
//! cubin is attributable to the toolchain rather than the algorithm.

use crate::ir::{Activation, KernelSpec, Reduce};
use std::fmt::Write;

pub const BLOCK_THREADS: i64 = 256;
pub const FULL_UNROLL_LIMIT: i64 = 64;

#[derive(Default)]
pub struct Emitter {
    out: String,
    r: u32,
    f: u32,
    p: u32,
    rd: u32,
    pub emitted_loads: u32,
    pub elided_guards: u32,
    axis_extents: Vec<i64>,
}

impl Emitter {
    fn next_r(&mut self) -> String { self.r += 1; format!("%r{}", self.r - 1) }
    fn next_f(&mut self) -> String { self.f += 1; format!("%f{}", self.f - 1) }
    fn next_p(&mut self) -> String { self.p += 1; format!("%p{}", self.p - 1) }
    fn next_rd(&mut self) -> String { self.rd += 1; format!("%rd{}", self.rd - 1) }
    fn l(&mut self, s: &str) { let _ = writeln!(self.out, "    {s}"); }

    /// Blocks needed to cover the spec's iteration space.
    pub fn grid_blocks(spec: &KernelSpec) -> u32 {
        ((spec.space.total_threads() + BLOCK_THREADS - 1) / BLOCK_THREADS) as u32
    }

    pub fn emit(&mut self, spec: &KernelSpec, major: u32, minor: u32) -> Result<String, String> {
        let space = &spec.space;
        let parallel = space.parallel_axes();
        let reduction = space.reduction_axes();
        let total = space.total_threads();
        let trips = space.reduction_trips();

        if trips > FULL_UNROLL_LIMIT {
            return Err(format!(
                "reduction trip count {trips} exceeds unroll limit {FULL_UNROLL_LIMIT}"
            ));
        }

        self.out.clear();
        self.elided_guards = 0;
        self.axis_extents = space.axes.iter().map(|a| a.extent).collect();
        let _ = writeln!(self.out, ".version 7.1");
        let _ = writeln!(self.out, ".target sm_{major}{minor}");
        let _ = writeln!(self.out, ".address_size 64\n");
        let _ = writeln!(self.out, "// generated by ptxgen (rust) from KernelSpec");
        let _ = writeln!(self.out, ".visible .entry {}(", spec.name);
        let pc = spec.param_count();
        for i in 0..pc {
            let sep = if i + 1 == pc { "" } else { "," };
            let _ = writeln!(self.out, "    .param .u64 p{i}{sep}");
        }
        let _ = writeln!(self.out, ")\n{{");
        let _ = writeln!(self.out, "    .reg .pred %p<256>;");
        let _ = writeln!(self.out, "    .reg .b32 %r<1024>;");
        let _ = writeln!(self.out, "    .reg .b64 %rd<512>;");
        let _ = writeln!(self.out, "    .reg .f32 %f<512>;");

        let mut base = Vec::with_capacity(pc);
        for i in 0..pc {
            let b = self.next_rd();
            self.l(&format!("ld.param.u64 {b}, [p{i}];"));
            base.push(b);
        }

        let ctaid = self.next_r();
        let tid = self.next_r();
        let gid = self.next_r();
        self.l(&format!("mov.u32 {ctaid}, %ctaid.x;"));
        self.l(&format!("mov.u32 {tid}, %tid.x;"));
        self.l(&format!("mad.lo.u32 {gid}, {ctaid}, {BLOCK_THREADS}, {tid};"));

        // Bounds guard from the same total_threads() the host launches with.
        let guard = self.next_p();
        self.l(&format!("setp.ge.u32 {guard}, {gid}, {total};"));
        self.l(&format!("@{guard} bra END;"));

        let mut axis_reg = vec![String::new(); space.axes.len()];
        let mut rest = gid;
        for (i, &ax) in parallel.iter().enumerate().rev() {
            let extent = space.axes[ax].extent;
            let reg = self.next_r();
            if i == 0 {
                self.l(&format!("mov.u32 {reg}, {rest};   // {}", space.axes[ax].name));
            } else {
                self.l(&format!("rem.u32 {reg}, {rest}, {extent};   // {}", space.axes[ax].name));
                let nr = self.next_r();
                self.l(&format!("div.u32 {nr}, {rest}, {extent};"));
                rest = nr;
            }
            axis_reg[ax] = reg;
        }

        let mut acc = self.next_f();
        if spec.reduce == Reduce::Max {
            self.l(&format!("mov.f32 {acc}, 0fFF800000;   // -inf"));
        } else {
            self.l(&format!("mov.f32 {acc}, 0f00000000;"));
        }

        let mut red_vals = vec![0i64; space.axes.len()];
        for t in 0..trips {
            let mut r = t;
            for &ra in reduction.iter().rev() {
                let e = space.axes[ra].extent;
                red_vals[ra] = r % e;
                r /= e;
            }

            let mut product: Option<String> = None;
            for &i in &spec.product_inputs {
                let binding = spec.inputs[i].clone();
                let v = self.emit_load(&binding, &base[binding.param], &axis_reg, &red_vals, &reduction);
                product = Some(match product {
                    None => v,
                    Some(prev) => {
                        let m = self.next_f();
                        self.l(&format!("mul.rn.f32 {m}, {prev}, {v};"));
                        m
                    }
                });
            }
            let product = product.expect("body needs at least one operand");

            if spec.reduce == Reduce::Max {
                self.l(&format!("max.f32 {acc}, {acc}, {product};"));
            } else {
                let na = self.next_f();
                self.l(&format!("add.rn.f32 {na}, {acc}, {product};"));
                acc = na;
            }
        }

        if let Some(b) = spec.bias_input {
            let binding = spec.inputs[b].clone();
            let v = self.emit_load(&binding, &base[binding.param], &axis_reg, &red_vals, &reduction);
            let na = self.next_f();
            self.l(&format!("add.rn.f32 {na}, {acc}, {v};"));
            acc = na;
        }
        if let Some(s) = spec.scale_input {
            let binding = spec.inputs[s].clone();
            let v = self.emit_load(&binding, &base[binding.param], &axis_reg, &red_vals, &reduction);
            let na = self.next_f();
            self.l(&format!("mul.rn.f32 {na}, {acc}, {v};"));
            acc = na;
        }
        if spec.activation == Activation::ReLU {
            self.l(&format!("max.f32 {acc}, {acc}, 0f00000000;"));
        }

        let output = spec.output.clone();
        let (off, pred) = self.emit_offset(&output, &axis_reg, &red_vals, &reduction);
        let byte = self.next_rd();
        let addr = self.next_rd();
        self.l(&format!("mul.wide.u32 {byte}, {off}, 4;"));
        self.l(&format!("add.u64 {addr}, {}, {byte};", base[output.param]));
        match pred {
            None => self.l(&format!("st.global.f32 [{addr}], {acc};")),
            Some(p) => self.l(&format!("@{p} st.global.f32 [{addr}], {acc};")),
        }

        let _ = writeln!(self.out, "END:\n    ret;\n}}");
        Ok(self.out.clone())
    }

    fn and_pred(&mut self, a: Option<String>, b: Option<String>) -> Option<String> {
        match (a, b) {
            (None, x) | (x, None) => x,
            (Some(x), Some(y)) => {
                let c = self.next_p();
                self.l(&format!("and.pred {c}, {x}, {y};"));
                Some(c)
            }
        }
    }

    fn emit_offset(
        &mut self,
        binding: &crate::ir::Binding,
        axis_reg: &[String],
        red_vals: &[i64],
        reduction: &[usize],
    ) -> (String, Option<String>) {
        let mut predicate: Option<String> = None;
        let mut offset: Option<String> = None;

        for (d, expr) in binding.map.iter().enumerate() {
            let dim = binding.shape[d];
            let stride = binding.stride(d);

            // Fold reduction-axis terms into the constant; keep parallel terms symbolic.
            let mut folded = expr.constant;
            let mut symbolic = Vec::new();
            for t in &expr.terms {
                if reduction.contains(&t.axis) {
                    folded += t.coeff * red_vals[t.axis];
                } else {
                    symbolic.push(*t);
                }
            }

            let num = if symbolic.is_empty() {
                let n = self.next_r();
                self.l(&format!("mov.u32 {n}, {folded};"));
                n
            } else {
                let mut acc: Option<String> = None;
                for t in &symbolic {
                    let c = if t.coeff == 1 {
                        axis_reg[t.axis].clone()
                    } else {
                        let m = self.next_r();
                        self.l(&format!("mul.lo.s32 {m}, {}, {};", axis_reg[t.axis], t.coeff));
                        m
                    };
                    acc = Some(match acc {
                        None => c,
                        Some(prev) => {
                            let s = self.next_r();
                            self.l(&format!("add.s32 {s}, {prev}, {c};"));
                            s
                        }
                    });
                }
                let mut n = acc.unwrap();
                if folded != 0 {
                    let s = self.next_r();
                    self.l(&format!("add.s32 {s}, {n}, {folded};"));
                    n = s;
                }
                n
            };

            let mut idx = num.clone();
            if expr.divisor != 1 {
                if expr.requires_exact {
                    let rem = self.next_r();
                    let pe = self.next_p();
                    self.l(&format!("rem.s32 {rem}, {num}, {};", expr.divisor));
                    self.l(&format!("setp.eq.s32 {pe}, {rem}, 0;"));
                    predicate = self.and_pred(predicate, Some(pe));
                }
                let q = self.next_r();
                self.l(&format!("div.s32 {q}, {num}, {};", expr.divisor));
                idx = q;
            }

            // Interval analysis over the folded expression -- see the C# emitter for
            // why the syntactic test is both unsound and wasteful.
            let (mut lo, mut hi) = (folded, folded);
            for t in &symbolic {
                let span = t.coeff * (self.axis_extents[t.axis] - 1);
                if t.coeff >= 0 { hi += span; } else { lo += span; }
            }
            let can_escape = expr.divisor != 1 || lo < 0 || hi >= dim;
            if !can_escape { self.elided_guards += 1; }
            if can_escape {
                let lo = self.next_p();
                let hi = self.next_p();
                let both = self.next_p();
                self.l(&format!("setp.ge.s32 {lo}, {idx}, 0;"));
                self.l(&format!("setp.lt.s32 {hi}, {idx}, {dim};"));
                self.l(&format!("and.pred {both}, {lo}, {hi};"));
                predicate = self.and_pred(predicate, Some(both));
            }

            offset = Some(match (offset, stride) {
                (None, 1) => idx,
                (None, s) => {
                    let m = self.next_r();
                    self.l(&format!("mul.lo.s32 {m}, {idx}, {s};"));
                    m
                }
                (Some(prev), 1) => {
                    let s = self.next_r();
                    self.l(&format!("add.s32 {s}, {prev}, {idx};"));
                    s
                }
                (Some(prev), st) => {
                    let m = self.next_r();
                    self.l(&format!("mad.lo.s32 {m}, {idx}, {st}, {prev};"));
                    m
                }
            });
        }

        (offset.expect("binding needs at least one dimension"), predicate)
    }

    fn emit_load(
        &mut self,
        binding: &crate::ir::Binding,
        base: &str,
        axis_reg: &[String],
        red_vals: &[i64],
        reduction: &[usize],
    ) -> String {
        let (off, pred) = self.emit_offset(binding, axis_reg, red_vals, reduction);
        let byte = self.next_rd();
        let addr = self.next_rd();
        let dst = self.next_f();
        self.l(&format!("mul.wide.s32 {byte}, {off}, 4;"));
        self.l(&format!("add.u64 {addr}, {base}, {byte};"));
        match pred {
            None => self.l(&format!("ld.global.nc.f32 {dst}, [{addr}];")),
            Some(p) => {
                self.l(&format!("mov.f32 {dst}, 0f00000000;"));
                self.l(&format!("@{p} ld.global.nc.f32 {dst}, [{addr}];"));
            }
        }
        self.emitted_loads += 1;
        dst
    }
}
