using System;
using AiDotNet.Tensors.Engines.DirectGpu;

namespace AiDotNet.Tensors.Engines.DirectGpu.HIP;

public sealed partial class HipBackend
{
    public void ReduceMean(IGpuBuffer i, IGpuBuffer o, int sz) { float[] d=DownloadBuffer(i); float s=0; for(int j=0;j<sz;j++)s+=d[j]; float[] r={s/sz}; UploadToExistingHip(r,o); }
    public unsafe void ClipKernel(IGpuBuffer i, IGpuBuffer o, float mn, float mx, int sz) { if(!_kernelCache.TryGetValue("clip_kernel",out var k)){float[] d=DownloadBuffer(i);float[] r=new float[sz];for(int j=0;j<sz;j++)r[j]=Math.Min(Math.Max(d[j],mn),mx);UploadToExistingHip(r,o);return;} IntPtr ip=i.Handle,op=o.Handle; void** a=stackalloc void*[5]; a[0]=&ip;a[1]=&op;a[2]=&mn;a[3]=&mx;a[4]=&sz; LaunchKernel(k,(uint)((sz+DefaultBlockSize-1)/DefaultBlockSize),DefaultBlockSize,a); }
    public unsafe void PowScalar(IGpuBuffer i, IGpuBuffer o, float ex, int sz) { if(!_kernelCache.TryGetValue("pow_scalar",out var k)){float[] d=DownloadBuffer(i);float[] r=new float[sz];for(int j=0;j<sz;j++)r[j]=MathF.Pow(d[j],ex);UploadToExistingHip(r,o);return;} IntPtr ip=i.Handle,op=o.Handle; void** a=stackalloc void*[4]; a[0]=&ip;a[1]=&op;a[2]=&ex;a[3]=&sz; LaunchKernel(k,(uint)((sz+DefaultBlockSize-1)/DefaultBlockSize),DefaultBlockSize,a); }
    public unsafe void FracKernel(IGpuBuffer i, IGpuBuffer o, int sz) { if(!_kernelCache.TryGetValue("frac_kernel",out var k)){float[] d=DownloadBuffer(i);float[] r=new float[sz];for(int j=0;j<sz;j++)r[j]=d[j]-MathF.Floor(d[j]);UploadToExistingHip(r,o);return;} IntPtr ip=i.Handle,op=o.Handle; void** a=stackalloc void*[3]; a[0]=&ip;a[1]=&op;a[2]=&sz; LaunchKernel(k,(uint)((sz+DefaultBlockSize-1)/DefaultBlockSize),DefaultBlockSize,a); }
    public void EyeKernel(IGpuBuffer o, int n) { float[] r=new float[n*n]; for(int j=0;j<n;j++) r[j*n+j]=1f; UploadToExistingHip(r,o); }
    public void OneHotKernel(IGpuBuffer idx, IGpuBuffer o, int bs, int nc) { float[] id=DownloadBuffer(idx); float[] r=new float[bs*nc]; for(int b=0;b<bs;b++) r[b*nc+(int)id[b]]=1f; UploadToExistingHip(r,o); }
    public void MaskedFillKernel(IGpuBuffer i, IGpuBuffer m, IGpuBuffer o, float fv, int sz) { float[] d=DownloadBuffer(i); float[] md=DownloadBuffer(m); float[] r=new float[sz]; for(int j=0;j<sz;j++) r[j]=md[j]!=0?fv:d[j]; UploadToExistingHip(r,o); }
    public unsafe void EqualsKernel(IGpuBuffer a1, IGpuBuffer b1, IGpuBuffer o, int sz) { if(!_kernelCache.TryGetValue("equals_kernel",out var k)){float[] ad=DownloadBuffer(a1);float[] bd=DownloadBuffer(b1);float[] r=new float[sz];for(int j=0;j<sz;j++)r[j]=ad[j]==bd[j]?1f:0f;UploadToExistingHip(r,o);return;} IntPtr ap=a1.Handle,bp=b1.Handle,op=o.Handle; void** a=stackalloc void*[4]; a[0]=&ap;a[1]=&bp;a[2]=&op;a[3]=&sz; LaunchKernel(k,(uint)((sz+DefaultBlockSize-1)/DefaultBlockSize),DefaultBlockSize,a); }
    public unsafe void NotEqualsKernel(IGpuBuffer a1, IGpuBuffer b1, IGpuBuffer o, int sz) { if(!_kernelCache.TryGetValue("not_equals_kernel",out var k)){float[] ad=DownloadBuffer(a1);float[] bd=DownloadBuffer(b1);float[] r=new float[sz];for(int j=0;j<sz;j++)r[j]=ad[j]!=bd[j]?1f:0f;UploadToExistingHip(r,o);return;} IntPtr ap=a1.Handle,bp=b1.Handle,op=o.Handle; void** a=stackalloc void*[4]; a[0]=&ap;a[1]=&bp;a[2]=&op;a[3]=&sz; LaunchKernel(k,(uint)((sz+DefaultBlockSize-1)/DefaultBlockSize),DefaultBlockSize,a); }
    public unsafe void OuterProduct(IGpuBuffer a1, IGpuBuffer b1, IGpuBuffer o, int M, int N) { if(!_kernelCache.TryGetValue("outer_product",out var k)){float[] ad=DownloadBuffer(a1);float[] bd=DownloadBuffer(b1);float[] r=new float[M*N];for(int i2=0;i2<M;i2++)for(int j=0;j<N;j++)r[i2*N+j]=ad[i2]*bd[j];UploadToExistingHip(r,o);return;} IntPtr ap=a1.Handle,bp=b1.Handle,op=o.Handle; void** a=stackalloc void*[5]; a[0]=&ap;a[1]=&bp;a[2]=&op;a[3]=&M;a[4]=&N; LaunchKernel(k,(uint)((M*N+DefaultBlockSize-1)/DefaultBlockSize),DefaultBlockSize,a); }
    public unsafe void BatchDotProduct(IGpuBuffer a1, IGpuBuffer b1, IGpuBuffer o, int bs, int dim) { if(!_kernelCache.TryGetValue("batch_dot_product",out var k)){float[] ad=DownloadBuffer(a1);float[] bd=DownloadBuffer(b1);float[] r=new float[bs];for(int i2=0;i2<bs;i2++){float s=0;for(int j=0;j<dim;j++)s+=ad[i2*dim+j]*bd[i2*dim+j];r[i2]=s;}UploadToExistingHip(r,o);return;} IntPtr ap=a1.Handle,bp=b1.Handle,op=o.Handle; void** a=stackalloc void*[5]; a[0]=&ap;a[1]=&bp;a[2]=&op;a[3]=&bs;a[4]=&dim; LaunchKernel(k,(uint)((bs+DefaultBlockSize-1)/DefaultBlockSize),DefaultBlockSize,a); }
    public unsafe void GluForward(IGpuBuffer i, IGpuBuffer o, int os, int hd) { if(!_kernelCache.TryGetValue("glu_forward",out var k)){float[] d=DownloadBuffer(i);float[] r=new float[os*hd];int fd=hd*2;for(int j=0;j<os;j++)for(int x=0;x<hd;x++){float v=d[j*fd+x];float g=d[j*fd+hd+x];r[j*hd+x]=v*(1f/(1f+MathF.Exp(-g)));}UploadToExistingHip(r,o);return;} IntPtr ip=i.Handle,op=o.Handle; void** a=stackalloc void*[4]; a[0]=&ip;a[1]=&op;a[2]=&os;a[3]=&hd; LaunchKernel(k,(uint)((os*hd+DefaultBlockSize-1)/DefaultBlockSize),DefaultBlockSize,a); }
    public unsafe void GeGluForward(IGpuBuffer i, IGpuBuffer o, int os, int hd) { if(!_kernelCache.TryGetValue("geglu_forward",out var k)){float[] d=DownloadBuffer(i);float[] r=new float[os*hd];int fd=hd*2;for(int j=0;j<os;j++)for(int x=0;x<hd;x++){float v=d[j*fd+x];float g=d[j*fd+hd+x];float x3=v*v*v;float gelu=0.5f*v*(1f+MathF.Tanh(0.7978845608f*(v+0.044715f*x3)));r[j*hd+x]=gelu*g;}UploadToExistingHip(r,o);return;} IntPtr ip=i.Handle,op=o.Handle; void** a=stackalloc void*[4]; a[0]=&ip;a[1]=&op;a[2]=&os;a[3]=&hd; LaunchKernel(k,(uint)((os*hd+DefaultBlockSize-1)/DefaultBlockSize),DefaultBlockSize,a); }
    public unsafe void ReGluForward(IGpuBuffer i, IGpuBuffer o, int os, int hd) { if(!_kernelCache.TryGetValue("reglu_forward",out var k)){float[] d=DownloadBuffer(i);float[] r=new float[os*hd];int fd=hd*2;for(int j=0;j<os;j++)for(int x=0;x<hd;x++)r[j*hd+x]=Math.Max(d[j*fd+x],0f)*d[j*fd+hd+x];UploadToExistingHip(r,o);return;} IntPtr ip=i.Handle,op=o.Handle; void** a=stackalloc void*[4]; a[0]=&ip;a[1]=&op;a[2]=&os;a[3]=&hd; LaunchKernel(k,(uint)((os*hd+DefaultBlockSize-1)/DefaultBlockSize),DefaultBlockSize,a); }
    public unsafe void SwiGluForward(IGpuBuffer i, IGpuBuffer o, int os, int hd) { if(!_kernelCache.TryGetValue("swiglu_forward",out var k)){float[] d=DownloadBuffer(i);float[] r=new float[os*hd];int fd=hd*2;for(int j=0;j<os;j++)for(int x=0;x<hd;x++){float v=d[j*fd+x];float sig=1f/(1f+MathF.Exp(-v));r[j*hd+x]=v*sig*d[j*fd+hd+x];}UploadToExistingHip(r,o);return;} IntPtr ip=i.Handle,op=o.Handle; void** a=stackalloc void*[4]; a[0]=&ip;a[1]=&op;a[2]=&os;a[3]=&hd; LaunchKernel(k,(uint)((os*hd+DefaultBlockSize-1)/DefaultBlockSize),DefaultBlockSize,a); }
    public void BceLoss(IGpuBuffer p, IGpuBuffer t, IGpuBuffer l, int sz) { float[] pd=DownloadBuffer(p); float[] td=DownloadBuffer(t); float[] r=new float[sz]; for(int j=0;j<sz;j++){float pc=Math.Min(Math.Max(pd[j],1e-7f),1f-1e-7f);r[j]=-(td[j]*MathF.Log(pc)+(1f-td[j])*MathF.Log(1f-pc));} UploadToExistingHip(r,l); }

    private void UploadToExistingHip(float[] data, IGpuBuffer buffer)
    {
        unsafe
        {
            fixed (float* src = data)
            {
                var sizeBytes = (UIntPtr)(data.Length * sizeof(float));
                HipNativeBindings.hipMemcpy(buffer.Handle, (IntPtr)src, sizeBytes, HipMemcpyKind.HostToDevice);
            }
        }
    }
    public void AddScalar(IGpuBuffer i, IGpuBuffer o, float sc, int sz) { float[] d=DownloadBuffer(i); float[] r=new float[sz]; for(int j=0;j<sz;j++) r[j]=d[j]+sc; UploadToExistingHip(r,o); }
    public void SubScalar(IGpuBuffer i, IGpuBuffer o, float sc, int sz) { float[] d=DownloadBuffer(i); float[] r=new float[sz]; for(int j=0;j<sz;j++) r[j]=d[j]-sc; UploadToExistingHip(r,o); }
    public void BroadcastAddLast(IGpuBuffer a, IGpuBuffer b, IGpuBuffer o, int os, int isz) { float[] ad=DownloadBuffer(a); float[] bd=DownloadBuffer(b); float[] r=new float[os*isz]; for(int j=0;j<os*isz;j++) r[j]=ad[j]+bd[j%isz]; UploadToExistingHip(r,o); }
    public void BroadcastSubLast(IGpuBuffer a, IGpuBuffer b, IGpuBuffer o, int os, int isz) { float[] ad=DownloadBuffer(a); float[] bd=DownloadBuffer(b); float[] r=new float[os*isz]; for(int j=0;j<os*isz;j++) r[j]=ad[j]-bd[j%isz]; UploadToExistingHip(r,o); }
    public void BroadcastMulLast(IGpuBuffer a, IGpuBuffer b, IGpuBuffer o, int os, int isz) { float[] ad=DownloadBuffer(a); float[] bd=DownloadBuffer(b); float[] r=new float[os*isz]; for(int j=0;j<os*isz;j++) r[j]=ad[j]*bd[j%isz]; UploadToExistingHip(r,o); }
    public void BroadcastDivLast(IGpuBuffer a, IGpuBuffer b, IGpuBuffer o, int os, int isz) { float[] ad=DownloadBuffer(a); float[] bd=DownloadBuffer(b); float[] r=new float[os*isz]; for(int j=0;j<os*isz;j++) r[j]=ad[j]/(bd[j%isz]+1e-12f); UploadToExistingHip(r,o); }
}
