// Copyright (c) AiDotNet. All rights reserved.

using System;
using AiDotNet.Tensors.Engines.Compilation.Codegen.Ir;
using AiDotNet.Tensors.Engines.Compilation.Codegen.Ptx;
using AiDotNet.Tensors.Engines.DirectGpu.CUDA.Ptx;
using Xunit;

namespace AiDotNet.Tensors.Tests.Engines.Codegen;

public sealed class CodegenOuterProductWinogradConv2DTests
{
    [Fact]
    public void BackwardData_RecoversExactPromotedSchedule()
    {
        var spec = CodegenKernelCatalog.Find("conv2d_3x3_bwd_data")!.Bench;
        var emitter = new PtxOuterProductWinogradConv2DEmitter();

        string ptx = emitter.Emit(spec, 8, 6);

        Assert.NotNull(emitter.Plan);
        Assert.Equal((8, 32, 28, 28, 64),
            (emitter.Plan!.Batch, emitter.Plan.M, emitter.Plan.OutputHeight,
             emitter.Plan.OutputWidth, emitter.Plan.ReductionChannels));
        Assert.Equal(64u, emitter.LaunchBlocks);
        Assert.Equal(256, emitter.LaunchBlockThreads);
        Assert.Equal(73728, emitter.SharedMemoryBytes);
        Assert.StartsWith(".version 7.1", ptx, StringComparison.Ordinal);
        Assert.Contains(".target sm_86", ptx);
        Assert.Contains("generated by PtxOuterProductWinogradConv2DEmitter", ptx);
        Assert.Contains("M32 x 32 tiles x F(2,3)", ptx);
        Assert.Contains("fma.rn.f32", ptx);
        Assert.DoesNotContain(".maxnreg", ptx);
        Assert.DoesNotContain("mma.sync", ptx);
        Assert.DoesNotContain("atom", ptx);
    }

    [Fact]
    public void InputPatch_UsesOneAlignedVectorLoadForAlwaysValidCentrePair()
    {
        var spec = CodegenKernelCatalog.Find("conv2d_3x3_bwd_data")!.Bench;
        string ptx = new PtxOuterProductWinogradConv2DEmitter().Emit(spec, 8, 6);

        // The initial and pipelined preload sites each contain four patch rows.
        // Every row keeps scalar boundary loads and combines the centre pair.
        Assert.Equal(8, Count(ptx, "ld.global.ca.v2.f32"));
        Assert.Equal(16, Count(ptx, "ld.global.ca.f32"));
        Assert.Contains("{%f97, %f98}, [%rd5+4]", ptx);
        Assert.Contains("{%f101, %f102}, [%rd5+116]", ptx);
        Assert.Contains("{%f105, %f106}, [%rd5+228]", ptx);
        Assert.Contains("{%f109, %f110}, [%rd5+340]", ptx);
    }

    [Fact]
    public void UnsupportedShapeAndArchitecture_AreRejectedBeforeEmission()
    {
        var verify = CodegenKernelCatalog.Find("conv2d_3x3_bwd_data")!.Verify;
        var bench = CodegenKernelCatalog.Find("conv2d_3x3_bwd_data")!.Bench;

        Assert.Throws<NotSupportedException>(
            () => new PtxOuterProductWinogradConv2DEmitter().Emit(verify, 8, 6));
        Assert.Throws<NotSupportedException>(
            () => new PtxOuterProductWinogradConv2DEmitter().Emit(bench, 7, 5));
    }

    [SkippableFact]
    public unsafe void BackwardData_LaunchAutomaticallyOptsIntoLargeDynamicSharedMemory()
    {
        Skip.IfNot(DirectPtxRuntime.IsAvailable, "Direct PTX runtime is unavailable.");
        using var runtime = new DirectPtxRuntime();
        Skip.If(runtime.ComputeCapabilityMajor < 8,
            "The outer-product Winograd pass requires sm_80+.");

        var spec = CodegenKernelCatalog.Find("conv2d_3x3_bwd_data")!.Bench;
        var emitter = new PtxOuterProductWinogradConv2DEmitter();
        string ptx = emitter.Emit(
            spec, runtime.ComputeCapabilityMajor, runtime.ComputeCapabilityMinor);
        using var module = runtime.LoadModule(ptx, allowExperimentalJitFallback: true);
        IntPtr function = module.GetFunction(emitter.EntryPoint!);
        using var matrix = runtime.AllocateBytes(
            (nuint)(spec.Inputs[emitter.Plan!.MatrixInput].ElementCount * sizeof(float)));
        using var stream = runtime.AllocateBytes(
            (nuint)(spec.Inputs[emitter.Plan.StreamInput].ElementCount * sizeof(float)));
        using var output = runtime.AllocateBytes(
            (nuint)(spec.Output.ElementCount * sizeof(float)));
        matrix.Upload<float>(new float[spec.Inputs[emitter.Plan.MatrixInput].ElementCount]);
        stream.Upload<float>(new float[spec.Inputs[emitter.Plan.StreamInput].ElementCount]);

        IntPtr p0 = matrix.Pointer, p1 = stream.Pointer, p2 = output.Pointer;
        void** arguments = stackalloc void*[3];
        arguments[spec.Inputs[emitter.Plan.MatrixInput].ParameterIndex] = &p0;
        arguments[spec.Inputs[emitter.Plan.StreamInput].ParameterIndex] = &p1;
        arguments[spec.Output.ParameterIndex] = &p2;
        module.Launch(function, emitter.LaunchBlocks, 1, 1,
            checked((uint)emitter.LaunchBlockThreads), 1, 1,
            checked((uint)emitter.SharedMemoryBytes), arguments);
        runtime.Synchronize();

        var actual = new float[spec.Output.ElementCount];
        output.Download<float>(actual);
        Assert.All(actual, value => Assert.Equal(0f, value));
    }

    private static int Count(string text, string value) =>
        text.Split(new[] { value }, StringSplitOptions.None).Length - 1;
}
