// Copyright (c) AiDotNet. All rights reserved.
// Roslyn incremental source generator (#775): emits one discoverable [SkippableFact] per
// tensor-returning IEngine op, each calling the runtime op-parity harness. The generated tests
// auto-sync with IEngine — add an op and it gets a parity test slot for free; ops without a
// registered spec emit a visible NEEDS-SPEC skip so full-surface coverage is auditable in the
// test explorer. This mirrors the ecosystem's source-generator approach; the actual input
// synthesis / tolerances live in the hand-tuned runtime registry (structured op args can't be
// invented from a signature alone).

using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace AiDotNet.Tensors.Tests.OpParityGen
{
    [Generator]
    public sealed class OpParityTestGenerator : IIncrementalGenerator
    {
        private const string EngineMetadataName = "AiDotNet.Tensors.Engines.IEngine";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var opNames = context.CompilationProvider.Select(static (compilation, _) => GetTensorReturningOps(compilation));
            context.RegisterSourceOutput(opNames, static (spc, names) => spc.AddSource("GeneratedOpParityTests.g.cs", Emit(names)));
        }

        private static IReadOnlyList<string> GetTensorReturningOps(Compilation compilation)
        {
            var engine = compilation.GetTypeByMetadataName(EngineMetadataName);
            if (engine is null) return System.Array.Empty<string>();

            var names = new SortedSet<string>(System.StringComparer.Ordinal);
            foreach (var member in engine.GetMembers().OfType<IMethodSymbol>())
            {
                if (member.DeclaredAccessibility != Accessibility.Public) continue;
                if (member.MethodKind != MethodKind.Ordinary) continue;
                var rt = member.ReturnType as INamedTypeSymbol;
                // Tensor<T> — the op surface the parity scaffold covers.
                if (rt is { IsGenericType: true, Name: "Tensor" }) names.Add(member.Name);
            }
            return names.ToList();
        }

        private static SourceText Emit(IReadOnlyList<string> opNames)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/> CPU-vs-GPU op-parity tests (#775). Do not edit.");
            sb.AppendLine("#if !NETFRAMEWORK");
            sb.AppendLine("using Xunit;");
            sb.AppendLine();
            sb.AppendLine("namespace AiDotNet.Tensors.Tests.Engines.OpParity");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>Generated: one discoverable parity fact per tensor-returning IEngine op.</summary>");
            sb.AppendLine("    [Collection(\"OpParity\")]");
            sb.AppendLine("    public sealed partial class GeneratedOpParityTests");
            sb.AppendLine("    {");
            sb.AppendLine("        private readonly OpParityFixture _fx;");
            sb.AppendLine("        public GeneratedOpParityTests(OpParityFixture fx) => _fx = fx;");
            sb.AppendLine();
            foreach (var op in opNames)
            {
                var method = Sanitize(op);
                sb.AppendLine("        [SkippableFact]");
                sb.AppendLine($"        public void Parity_{method}() => GeneratedOpParitySupport.RunForwardByMethod(\"{op}\", _fx);");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine("#endif");
            return SourceText.From(sb.ToString(), Encoding.UTF8);
        }

        private static string Sanitize(string name)
        {
            var chars = name.ToCharArray();
            for (int i = 0; i < chars.Length; i++)
                if (!char.IsLetterOrDigit(chars[i]) && chars[i] != '_') chars[i] = '_';
            return new string(chars);
        }
    }
}
